"""The GENERATED single-implementation packet, driven through real boundaries.

WHAT IS REAL HERE. `baseline_bindings.compose` and `write` produce the
deployment, the sealed input manifest, the candidate context profile, the
submission and `PACKET.json`; `stage_execution.held_configuration` and
`operations_from` read THOSE bytes; and `baseline.supervise` drives them
through `held_packet`, the owner acts, the admission gate, the real worker
turn, the cancellation seam, the ending driver and the cleanup accounting. The
Authority is a fresh disposable one built through public APIs, which is
ordinary deterministic fixture setup and touches no deployed instance.

WHAT IS NOT CLAIMED. The engine and the provider subprocess remain the two
accepted deterministic seams. No container, no image, no live provider, no
network, no credential, and no operator deployment is read or changed.

WHY COMPOSITION IS CHECKED HERE AND NOT ONLY DESCRIBED. W236087's packet was
validated document by document and then produced a live run whose shape nobody
had exercised end to end. The composition cases below assert the three
decisions the split ruling actually made -- one submitted stage, one admitted
container, and no review vocabulary in the run's own outcome -- and the driving
case then runs those exact bytes.

A REVIEW WORKER IS STILL CONFIGURED, because `stage_execution` refuses a
deployment that names none: "a Job that cannot be produced or independently
reviewed serves nothing". Deleting it to make this Job look smaller would be
relaxing an independence invariant to pass a validator. So what the driving
case establishes is the stronger statement -- a reviewer was configured and
launchable, and this run started exactly one container anyway.
"""
import json
import os
from pathlib import Path
import unittest
from unittest import mock

from baton_v12.contracts import digest
from tests.job_manager import fixtures
from tools import single_worker, stage_execution

import baseline
import baseline_bindings
from test_baseline import BaselineCase, TURN_SECONDS

HERE = Path(__file__).resolve().parent
CHECKOUT = str(HERE.parents[4])
VECTORS = (Path(CHECKOUT) / "work/records/2026/08"
           / "finding-v12-isolated-agent-workers/findings"
           / "finding-v12-worker-contract/findings"
           / "finding-worker-control-api-manifests/evidence/vectors.json")
NETWORK = "baton-provider-egress"
# THE TREE THE SUPERVISOR'S OWN PROCESS REALLY IMPORTS. `baton_v12` resolves to
# `<PYTHON>/src/baton_v12` and `tools` to `<PYTHON>/tools`, so binding this root
# is binding the bytes this process is running -- which is what makes
# `verify_imported_sources` a proof here rather than a formality over a
# synthetic package.
PYTHON = Path(CHECKOUT) / "v12/python"


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheGeneratedPacketDrivesOneImplementation(BaselineCase):
    """One run, composed from the packet's own generated bytes.

    `generated` is a CLASS attribute so it exists before `setUp` runs: the
    inherited fixture asks for the composed document while building its own
    packet, which is the earliest this composition is reached.
    """

    generated = None

    def setUp(self):
        self.generated = None
        super().setUp()

    # -- the deployment under test IS the generated one ----------------------

    def selections(self):
        """Every operand, taken from THIS case's own disposable identities.

        The participants, principals, routes and grants are the ones the
        fixture registered against its fresh Authority; the workspace, launch
        and credential roots are the ones this composition already configured.
        Nothing here points at an operator deployment.
        """
        return {
            "instance": {
                "authority_store": self.authority_path,
                "authority_uuid": self.config["authority_uuid"],
                "integration_store": self.integration_store,
                "job_store": os.path.join(self.root, "jobs.sqlite3"),
                "control_store": os.path.join(self.root, "control.sqlite3"),
                "integration_profile": {
                    "profile_kind": "git", "profile_version": 1,
                    "integrator_participant": "baton.integrator",
                    "instructions_digest": "sha256:" + "e" * 64},
                "retention_policy_digest":
                    self.config["retention_policy_digest"],
                "runtime_path": self.written_runtime_root(),
                "build_commit": "c97fe766000000000000000000000000000000ab"},
            "source_root": self.source,
            "image_reference": "baton-v12-claude-worker:deterministic",
            "image_digest": self.config["image_digest"],
            "cli_build": "2.1.247",
            "manager_source": self.written_manager_source(),
            "supervisor_path": str(HERE / "baseline.py"),
            "vectors": str(VECTORS),
            "credential_sources": None,
            "credential_profile": {"api": {"provider": "fixture",
                                           "reference": "fixture/one"}},
            "evidence_digest": digest({"deterministic": "composition proof"}),
            "provider_network": NETWORK,
            "code_boundary": self.written_manager_source(),
            "run_id": self.RUN, "work": "W239528", "claim": 239653,
            "note": "the generated baseline packet, driven deterministically",
            "places": {"workspaces": self.storage,
                       "private-contexts": str(self.context_root)},
            "participants": {
                "work_id": self.work,
                "implementation": self.config["participant"],
                "implementation_principal": self.config["principal"],
                # CONFIGURED AND NEVER ADMITTED. The manager's validator
                # requires a review worker; this run submits no review stage.
                "review": "baton.reviewer",
                "review_principal": self.principals["baton.reviewer"],
                "receipts": {"verification": "baton.verifier",
                             "review": "baton.approver-review",
                             "approval": "baton.approver"},
                "worker_files": {"opt/baton/claude_agent.py": "0" * 64},
                "fixture_files": {"harness.py": self.digest_of(
                    os.path.join(self.source, "harness.py"))}}}

    def written_runtime_root(self):
        place = self.packet_root / "runtime"
        place.mkdir(exist_ok=True)
        (place / "baton-v12-stack").write_bytes(b"#!/bin/sh\nexit 0\n")
        return str(place)

    def written_manager_source(self):
        """A REAL importable tree, bound file by file, and a SMALL one.

        The production packet binds `baton_v12` and `tools`. Binding this
        checkout's `v12/python` here instead would hash every transient
        scratch directory the test process creates under it, so what this
        exercises is the composer's file-by-file binding rather than the size
        of the tree it is pointed at. `test_baseline` covers the import-
        location refusal that the production binding exists for.
        """
        place = self.packet_root / "manager-source"
        (place / "boundpkg").mkdir(parents=True, exist_ok=True)
        (place / "boundpkg" / "__init__.py").write_text(
            "VERSION = 'bound'\n", encoding="utf-8")
        return str(place)

    def generate(self):
        """Compose and WRITE the packet, exactly as the operator command does."""
        if self.generated is None:
            self.run_root = os.path.join(self.root, "generated-run")
            documents = baseline_bindings.compose(
                base=self.base, run_root=self.run_root, **self.selections())
            places = baseline_bindings.write(self.run_root, documents,
                                             checkout=self.checkout)
            # THE CERTIFIED PROFILE IS THE GENERATED ONE, and so is the
            # submission: every stage is compared against the Job's single
            # input digest and against the worker's configured policy and
            # profile, so a submission composed from the accepted fixture's
            # manifest could be served by no worker this deployment configures.
            if "context-profile.json" in documents:
                self.context_profile = documents["context-profile.json"]
                self.context_digest = digest(self.context_profile)
            self.submission = documents["submission.json"]
            self.generated = (documents, places)
        return self.generated

    def composed_document(self, **members):
        """THE GENERATED DEPLOYMENT, not the accepted test fixture's.

        This is the substitution the whole case exists to make: everything
        downstream -- the preflight, the sessions, the pool, the launch
        documents, the mounts and the endings -- reads bytes
        `baseline_bindings` produced.
        """
        del members
        documents, _places = self.generate()
        return documents["deployment.json"]

    def turn(self, control, role, attempt_id, roots, **operands):
        """One worker turn, adopted from the GENERATED launch home."""
        documents, _places = self.generate()
        workers = {one["role"]: one["deployment"]
                   for one in documents["deployment.json"]["workers"]}
        held = self.config["launch_home"]
        self.config["launch_home"] = workers[role]["launch_home"]
        try:
            return super().turn(control, role, attempt_id, roots, **operands)
        finally:
            self.config["launch_home"] = held

    def packet_for(self):
        """The generated `PACKET.json`, adapted to this case's own context.

        Two members are this fixture's rather than the composer's: the context
        profile the accepted harness certifies, and the submission the
        supervised case submits. Everything else -- the bounds, the fixture
        binding, the manager source, the deployment path and digest -- is the
        generated packet's own.
        """
        _documents, places = self.generate()
        packet = json.loads(Path(places["PACKET.json"]).read_text(
            encoding="utf-8"))
        if packet["schema"] == baseline.PACKET_SCHEMA:
            packet["context"].update(
                profile_path=str(self.packet_root / "profile.json"),
                profile_sha256=self.digest_of(str(self.packet_root
                                                  / "profile.json")),
                profile_digest=self.context_digest,
                storage_path=str(self.context_root))
        packet["submission"] = dict(
            packet["submission"],
            path=str(self.packet_root / "submission.json"),
            sha256=self.digest_of(str(self.packet_root / "submission.json")))
        packet["deployment"].update(
            job_store=str(Path(self.root) / "jobs.sqlite3"),
            control_store=str(Path(self.root) / "control.sqlite3"),
            authority_store=str(self.authority_path),
            authority_uuid=self.config["authority_uuid"],
            state_root=str(self.root))
        packet["outcome_path"] = str(self.packet_root
                                     / "generated-outcome.json")
        place = self.packet_root / "GENERATED-PACKET.json"
        place.write_text(json.dumps(packet, sort_keys=True, indent=2),
                         encoding="utf-8")
        self.generated_packet_path = str(place)
        return packet

    # -- the whole path, in one run -----------------------------------------

    def test_the_generated_deployment_produces_one_attributed_proposal(self):
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["state"], "settled", outcome["held_because"])
        self.assertEqual(outcome["stopped"], "completed")
        self.assertEqual(outcome["workload"]["shortfalls"], [])
        self.assertEqual(outcome["workload"]["modes"], ["open"])
        self.assertEqual(len(outcome["workload"]["proposals"]), 1)
        self.assertEqual(outcome["outstanding_cleanup"], [])
        self.assertEqual(outcome["uncertainty"], [])
        self.assertIs(outcome["final_canonical_read"], True)
        said = outcome["workload"]["attribution"][0]
        self.assertEqual(said["author"],
                         f"{baseline.COMMIT_NAME} <{baseline.COMMIT_EMAIL}>")
        self.assertEqual(said["parents"], [self.base])
        # THE PROVIDER WAS CALLED ONCE AND NOTHING WAS RESUMED.
        calls = [json.loads(line)
                 for line in self.calls.read_text().splitlines()]
        self.assertEqual([one["restored"] for one in calls], [False])

    def test_the_generated_packet_is_the_one_held_packet_accepts(self):
        packet = self.packet_for()
        held = baseline.held_packet(self.generated_packet_path)
        self.assertEqual(held["bounds"], packet["bounds"])
        self.assertEqual(held["bounds"]["implementer_invocations"], 1)
        self.assertEqual(held["deployment"]["config_sha256"],
                         self.digest_of(held["deployment"]["config_path"]))

    def test_the_generated_deployment_passes_the_managers_own_validator(self):
        """Both roles are CONFIGURED, because the manager requires a
        deployment that could independently review; only one is ever
        admitted."""
        documents, _places = self.generate()
        given = stage_execution.held_configuration(
            documents["deployment.json"], checkout=self.checkout)
        self.assertEqual(sorted(one["role"] for one in given["workers"]),
                         ["implementation", "review"])
        for one in given["workers"]:
            with self.subTest(role=one["role"]):
                self.assertEqual(one["deployment"]["network"], NETWORK)

    def test_a_reviewer_was_available_and_this_run_started_no_container(self):
        """The proof is not "no reviewer existed". It is that one was
        configured, launchable, and never admitted."""
        packet = self.packet_for()
        documents, _places = self.generate()
        self.assertIn("review", [one["role"] for one
                                 in documents["deployment.json"]["workers"]])
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["admissions"], {"implementation": 1})
        self.assertEqual(outcome["stage_states"],
                         {"implementation": "completed"})
        self.assertEqual(len(outcome["admitted_attempts"]), 1)
        self.assertEqual(outcome["workload"]["shortfalls"], [])

    def test_the_completed_attempt_is_not_ordered_stopped(self):
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(len(outcome["admitted_attempts"]), 1)
        for attempt, held in sorted(outcome["cancellation"].items()):
            with self.subTest(attempt=attempt):
                self.assertTrue(held["requested"])
                self.assertNotIn("answer", held)
                self.assertIn("this manager observed the runtime", held["why"])
                self.assertEqual(held["execution_runtime"], "destroyed")

    def test_a_timeout_over_generated_bytes_stops_and_accounts(self):
        """The failure path of the same composition, in the same run shape."""
        packet = dict(self.packet_for(), bounds=dict(
            self.packet["bounds"], total_seconds=8, cleanup_seconds=3))
        job, control, composed = self.serving()
        ticks = iter(range(10000))
        outcome = baseline.supervise(
            job, control, composed, packet, clock=lambda: fixtures.NOW,
            sleep=lambda seconds: None,
            monotonic=lambda: float(next(ticks)))
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        self.assertEqual(outcome["state"], "held")
        executing = [one for one, held in outcome["cancellation"].items()
                     if held.get("execution_runtime") == "running"]
        self.assertTrue(executing, outcome["cancellation"])
        for attempt in executing:
            self.assertTrue(outcome["cancellation"][attempt]["requested"])

    def test_the_preflight_asks_about_every_configured_participant(self):
        """The deployment resolves principals for every worker it configures,
        so an unresolvable review principal refuses the composition whether or
        not a review container is ever started."""
        documents, _places = self.generate()
        from baton_v12.authority import Authority

        authority = Authority.open(
            self.authority_path,
            expected_authority_uuid=self.config["authority_uuid"])
        try:
            missing = baseline_bindings.preflight(
                authority, documents, self.selections()["participants"])
        finally:
            authority.dispose()
        body = "\n".join(missing)
        self.assertIn("`impl` handler registration", body)
        self.assertIn("submits no review stage", body)
        self.assertNotIn("implementation participant", body)
        self.assertNotIn("review participant", body)


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheCompositionCarriesOnlyThisJobsWorkload(TheGeneratedPacketDrivesOneImplementation):
    """The split ruling, asserted over the emitted documents themselves."""

    def test_the_submission_declares_one_stage_with_no_dependency(self):
        documents, _places = self.generate()
        jobs = documents["submission.json"]["jobs"]
        self.assertEqual(len(jobs), 1)
        stages = jobs[0]["stages"]
        self.assertEqual([one["kind"] for one in stages], ["implementation"])
        self.assertEqual(stages[0]["depends_on"], [])
        self.assertEqual(jobs[0]["execution_limits"],
                         {"provider_turn_seconds": TURN_SECONDS})

    def worker_document(self, role="implementation"):
        documents, _places = self.generate()
        return next(one["deployment"] for one
                    in documents["deployment.json"]["workers"]
                    if one["role"] == role)

    def test_the_manifest_declares_the_proposal_required_and_no_findings(self):
        """`IMPLEMENTATION_OUTPUTS` is exactly `("proposal",)`; `findings` and
        `logs` are the review turn's, and this Job runs no review turn."""
        manifest = self.worker_document()["input_manifest"]
        declared = {one["name"]: one for one in manifest["outputs"]}
        self.assertEqual(sorted(declared),
                         ["propos" + "al", "provider-context-receipt"])
        self.assertIs(declared["proposal"]["required"], True)
        self.assertIs(declared["provider-context-receipt"]["required"], False)

    def test_the_task_document_states_requirements_and_owns_the_commit(self):
        """W236087's four-stage script is the defect this replaces. The
        instructions must carry no stage script, and must say who commits."""
        documents, _places = self.generate()
        instructions = documents["task.json"]["instructions"]
        for word in ("FIRST REVIEW", "FINAL REVIEW", "CORRECTION",
                     "Verdict", "ACCEPTANCE.md"):
            with self.subTest(word=word):
                self.assertNotIn(word, instructions)
        self.assertIn("Do not review, assess or grade your own work",
                      instructions)
        self.assertIn("EDIT THE FILES; DO NOT COMMIT THEM", instructions)
        self.assertIn("git commit", instructions)

    def test_the_fixture_carries_no_acceptance_or_feedback_document(self):
        """The one live run that shipped those documents had its
        implementation agent read them and grade itself against them."""
        self.assertEqual(sorted(baseline_bindings.FIXTURE_DOCUMENTS),
                         ["TASK.md", "harness.py"])

    def test_the_bounds_name_no_review_or_correction_member(self):
        documents, _places = self.generate()
        self.assertEqual(sorted(documents["PACKET.json"]["bounds"]),
                         ["cleanup_seconds", "implementer_invocations",
                          "retry", "total_seconds", "turn_seconds"])

    def test_the_task_bytes_are_exactly_what_the_manifest_seals(self):
        from baton_v12.contracts import digest_of_bytes

        _documents, places = self.generate()
        body = Path(places["task.json"]).read_bytes()
        contract = self.worker_document()["input_manifest"]["human_contract"]
        self.assertEqual(contract["bytes"], len(body))
        self.assertEqual(contract["content_digest"], digest_of_bytes(body))

    def test_the_worker_document_is_the_contextual_schema(self):
        held = self.worker_document()
        self.assertEqual(held["schema"], single_worker.CONTEXT_CONFIG_SCHEMA)
        self.assertEqual(held["provider_context"]["mode"], "required")
        self.assertEqual(held["launch_role"], "implementation")
        self.assertEqual(held["review_route"], "rview")

    def test_the_two_roles_share_no_participant_or_principal(self):
        """`_independent` refuses this at the configuration, before anything
        is opened; asserting it here is asserting what was composed."""
        held = self.worker_document()
        other = self.worker_document("review")
        self.assertNotEqual(held["participant"], other["participant"])
        self.assertNotEqual(held["principal"], other["principal"])
        self.assertNotIn("provider_context", other)


class TheComposerRefusesWhatItCannotHold(unittest.TestCase):
    """Every refusal below is reached before a document is written."""

    def operands(self, **overrides):
        held = {"instance": {}, "run_root": "/tmp/nowhere",
                "source_root": "/tmp/source", "base": "a" * 40,
                "image_reference": "image", "image_digest": "sha256:" + "0" * 64,
                "cli_build": "2.1.247", "manager_source": str(PYTHON),
                "supervisor_path": str(HERE / "baseline.py"),
                "vectors": str(VECTORS), "participants": {},
                "credential_sources": None, "credential_profile": {},
                "evidence_digest": "sha256:" + "b" * 64,
                "provider_network": NETWORK, "run_id": "r", "work": "W239528",
                "claim": 1, "note": "n", "code_boundary": CHECKOUT}
        held.update(overrides)
        return held

    def refusal(self, **overrides):
        with self.assertRaises(baseline_bindings.BindingRefusal) as caught:
            baseline_bindings.compose(**self.operands(**overrides))
        return str(caught.exception)

    def test_review_bounds_are_refused_by_name(self):
        said = self.refusal(bounds=dict(baseline_bindings.BOUNDS,
                                        review_invocations=2, corrections=1))
        self.assertIn("corrections, review_invocations", said)
        self.assertIn("its review is a separate Job", said)

    def test_a_second_implementer_invocation_is_refused(self):
        said = self.refusal(bounds=dict(baseline_bindings.BOUNDS,
                                        implementer_invocations=2))
        self.assertIn("ONE implementation container", said)

    def test_a_placeholder_base_is_refused(self):
        said = self.refusal(base="not-an-object")
        self.assertIn("one full lower-case object name", said)

    def test_a_network_that_could_never_reach_the_provider_is_refused(self):
        said = self.refusal(provider_network="none")
        self.assertIn("could never answer the question", said)

    def test_a_sentinel_evidence_digest_is_refused(self):
        said = self.refusal(evidence_digest="sha256:" + "0" * 64)
        self.assertIn("is a sentinel", said)

    def test_a_code_boundary_that_does_not_contain_the_source_is_refused(self):
        said = self.refusal(code_boundary="/tmp")
        self.assertIn("would not protect the code the run imports", said)


class TheFreshPacket(TheGeneratedPacketDrivesOneImplementation):
    """Plain worker path; fixture engine/provider only, no context qualification."""

    def selections(self):
        selected = super().selections()
        selected.update(context_mode="fresh", task_instructions="Change harness.py to print READY, produce a proposal; do not commit yourself.", verification=["python3", "harness.py"])
        return selected

    def provider(self, edits=None, status=0):
        from tests.tools.test_stage_execution import ComposedOneJobCase
        return ComposedOneJobCase.provider(self, edits=edits, status=status)

    def test_fresh_documents_and_reader_have_no_context_contract(self):
        docs, places = self.generate()
        self.assertNotIn("context-profile.json", docs)
        self.assertFalse(Path(self.run_root, "context-profile.json").exists())
        held = baseline.held_packet(places["PACKET.json"])
        self.assertEqual(held["schema"], baseline.FRESH_PACKET_SCHEMA)
        self.assertEqual(held["context"], {"mode": "fresh"})
        for worker in docs["deployment.json"]["workers"]:
            self.assertEqual(worker["deployment"]["schema"], single_worker.CONFIG_SCHEMA)
            self.assertNotIn("provider_context", worker["deployment"])
            self.assertEqual([o["name"] for o in worker["deployment"]["input_manifest"]["outputs"]], ["proposal"])
        self.assertEqual(docs["submission.json"]["jobs"][0]["execution_limits"], {"provider_turn_seconds": 180, "verification_command_seconds": 30})

    def test_fresh_prepare_never_certifies_or_grants_context(self):
        from baton_v12.worker_manager import provider_context, context_delivery
        packet = self.packet_for()
        _job, control = self.stores("fresh-prepare")
        with mock.patch.object(provider_context, "certify_context_profile", side_effect=AssertionError("context certification")), mock.patch.object(provider_context, "authorize_qualification_run", side_effect=AssertionError("context grant")), mock.patch.object(context_delivery, "configure_context_storage", side_effect=AssertionError("context storage")):
            answer = baseline.prepare(control, packet)
        self.assertEqual(answer, {"workspace_storage": self.storage, "context_mode": "fresh"})

    def test_fresh_packet_cannot_hide_contextual_worker(self):
        docs, places = self.generate()
        configured = docs["deployment.json"]
        configured["workers"][0]["deployment"]["provider_context"] = {"mode": "required"}
        Path(places["deployment.json"]).write_text(json.dumps(configured))
        packet = json.loads(Path(places["PACKET.json"]).read_text())
        packet["deployment"]["config_sha256"] = self.digest_of(places["deployment.json"])
        Path(places["PACKET.json"]).write_text(json.dumps(packet))
        with self.assertRaisesRegex(baseline.SupervisorRefusal, "plain workers"):
            baseline.held_packet(places["PACKET.json"])

    def test_literal_composer_command_emits_a_fresh_packet(self):
        import io
        selected = self.selections()
        run = str(Path(self.root) / "literal-fresh")
        selection_path = Path(self.root) / "fresh-selections.json"
        selection_path.write_text(json.dumps({"compose": selected}))
        argv = ["--selections", str(selection_path), "--base", self.base, "--run-root", run]
        self.assertEqual(baseline_bindings.main(argv, stream=io.StringIO()), 0)
        packet = baseline.held_packet(str(Path(run) / "PACKET.json"))
        self.assertEqual(packet["context"], {"mode": "fresh"})

    def test_generated_start_refuses_mixed_mode_before_store_or_engine(self):
        import io
        from baton_v12.job_manager import JobStore
        docs, places = self.generate()
        commands = json.loads(Path(places["commands.json"]).read_text())
        self.assertEqual(commands["start"][:3], [baseline_bindings.sys.executable, "-B", str(HERE / "baseline.py")])
        packet = json.loads(Path(places["PACKET.json"]).read_text())
        packet["context"] = {"mode": "contextual"}
        Path(places["PACKET.json"]).write_text(json.dumps(packet))
        stream = io.StringIO()
        with mock.patch.object(JobStore, "open", side_effect=AssertionError("store opened")):
            answer = baseline.main(commands["start"][3:], stream=stream, image_inspect=lambda ref: self.fail("engine inspected"))
        self.assertEqual(answer, 2)
        self.assertIn("explicit fresh context mode", stream.getvalue())

    def test_generated_start_refuses_changed_fixture_before_store_or_engine(self):
        self._generated_start_refuses_drift(Path(self.source) / "harness.py")

    def test_generated_start_refuses_changed_manager_source_before_store_or_engine(self):
        self._generated_start_refuses_drift(Path(self.written_manager_source()) / "boundpkg" / "__init__.py")

    def _generated_start_refuses_drift(self, changed):
        import io
        from baton_v12.job_manager import JobStore
        from baton_v12.worker_manager import ControlStore
        _docs, places = self.generate()
        commands = json.loads(Path(places["commands.json"]).read_text())
        changed.write_bytes(changed.read_bytes() + b"\n# changed after binding\n")
        preserved = changed.read_bytes()
        stream = io.StringIO()
        with mock.patch.object(JobStore, "open", side_effect=AssertionError("Job store opened")), mock.patch.object(ControlStore, "open", side_effect=AssertionError("control store opened")):
            answer = baseline.main(commands["start"][3:], stream=stream, image_inspect=lambda ref: self.fail("engine inspected"))
        self.assertEqual(answer, 2)
        self.assertIn("refused before anything opened", stream.getvalue())
        self.assertIn(str(changed), stream.getvalue())
        self.assertIn("this packet is bound to", stream.getvalue())
        self.assertEqual(changed.read_bytes(), preserved)

    def test_literal_failure_logs_report_inaccessibility_not_empty_capture(self):
        import io
        from tools import stack_command
        stream = io.StringIO()
        with mock.patch("sys.stdout", stream):
            code = stack_command.main(["logs", "--logs", str(Path(self.root) / "never-created-logs"), "--attempt", "never-launched", "locators"])
        self.assertEqual(code, 0)
        observed = json.loads(stream.getvalue())
        self.assertTrue(observed["streams"])
        self.assertEqual({one["state"] for one in observed["streams"]}, {"inaccessible"})
        self.assertTrue(all("FileNotFoundError" in one["why"] for one in observed["streams"]))

    def test_fresh_submission_cannot_add_a_second_job(self):
        docs, places = self.generate()
        submission = docs["submission.json"]
        submission["jobs"].append(dict(submission["jobs"][0], job_id="other"))
        Path(places["submission.json"]).write_text(json.dumps(submission))
        packet = json.loads(Path(places["PACKET.json"]).read_text())
        packet["submission"]["sha256"] = self.digest_of(places["submission.json"])
        Path(places["PACKET.json"]).write_text(json.dumps(packet))
        with self.assertRaisesRegex(baseline.SupervisorRefusal, "exactly one implementation Job"):
            baseline.held_packet(places["PACKET.json"])

    def test_fresh_composer_preserves_an_existing_packet(self):
        docs, places = self.generate()
        before = {name: Path(path).read_bytes() for name, path in places.items()}
        with self.assertRaisesRegex(baseline_bindings.BindingRefusal, "destination already exists"):
            baseline_bindings.write(self.run_root, docs)
        self.assertEqual({name: Path(path).read_bytes() for name, path in places.items()}, before)

    def test_fresh_deadline_reserves_cleanup_before_any_admission(self):
        from baton_v12 import job_manager
        packet = self.packet_for()
        job, control, composed = self.serving(packet=packet)
        elapsed = [0.0]

        def serving_ticks(_job, gate, **arguments):
            elapsed[0] = packet["bounds"]["total_seconds"] - packet["bounds"]["cleanup_seconds"] - 1
            self.assertTrue(arguments["should_continue"]())
            elapsed[0] += 1
            self.assertFalse(arguments["should_continue"]())
            self.assertEqual(gate.admissions, {"implementation": 0})

        with mock.patch.object(job_manager, "serve", side_effect=serving_ticks):
            outcome = baseline.supervise(job, control, composed, packet, clock=lambda: fixtures.NOW, sleep=lambda seconds: self.fail("unexpected wait"), monotonic=lambda: elapsed[0])
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        self.assertEqual(outcome["served_seconds"], 240)
        self.assertEqual(outcome["admissions"], {"implementation": 0})
        self.assertIsNone(outcome["serving_failure"])
        self.assertNotEqual(outcome["state"], "settled")

    def test_fresh_positive_one_proposal_without_context(self):
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["state"], "settled", repr([(single_worker.attempt_preparation_failure_of(_control, a), single_worker.attempt_start_failure_of(_control, a)) for a in outcome["admitted_attempts"]]))
        self.assertEqual(outcome["admissions"], {"implementation": 1})
        self.assertEqual(len(outcome["workload"]["proposals"]), 1)
        self.assertEqual(outcome["workload"]["modes"], [])
        self.assertEqual(outcome["workload"]["shortfalls"], [])
        self.assertEqual(outcome["outstanding_cleanup"], [])


class TheFreshCommandsInSubprocesses(TheFreshPacket):
    """Literal generated argv/environment; fake Docker executable, no daemon.

    These are preflight proofs, not a completed Job or runtime cessation proof.
    The engine executable fails closed and cannot dispatch a real workload.
    """

    def written_manager_source(self):
        import shutil
        # The unfrozen observer derives its checkout from tools/../../..;
        # preserve the source distribution's v12/python directory layout.
        place = self.packet_root / "complete-manager-source/v12/python"
        if not place.exists():
            for relative in ("src/baton_v12", "tools"):
                shutil.copytree(PYTHON / relative, place / relative, ignore=shutil.ignore_patterns("__pycache__"))
        return str(place)

    def run_generated_start(self, *, drift=False):
        import subprocess
        import sys
        _docs, places = self.generate()
        commands = json.loads(Path(places["commands.json"]).read_text())
        packet = json.loads(Path(places["PACKET.json"]).read_text())
        fake_bin = Path(self.root) / "fake-engine-bin"
        fake_bin.mkdir()
        calls = Path(self.root) / "engine-calls.json"
        executable = fake_bin / "docker"
        executable.write_text("#!" + sys.executable + "\nimport json,sys\nfrom pathlib import Path\nPath(" + repr(str(calls)) + ").write_text(json.dumps(sys.argv[1:]))\nraise SystemExit(1)\n")
        executable.chmod(0o700)
        environment = dict(os.environ, **commands["environment"])
        # No real executable fallback; all engine invocations hit this boundary.
        environment["PATH"] = str(fake_bin)
        if drift:
            changed = Path(packet["manager_source"]["path"]) / "tools/__init__.py"
            changed.write_bytes(changed.read_bytes() + b"\n# post-binding drift\n")
        stores = [Path(packet["deployment"][name]) for name in ("job_store", "control_store")]
        before = {str(p): p.read_bytes() if p.exists() else None for p in stores}
        answer = subprocess.run(commands["start"], env=environment, cwd=self.root, capture_output=True, text=True, timeout=20)
        self.assertEqual(answer.returncode, 2, answer.stderr)
        self.assertIn("refused before anything opened", answer.stderr)
        self.assertNotIn("Traceback", answer.stderr)
        self.assertEqual({str(p): p.read_bytes() if p.exists() else None for p in stores}, before)
        if drift:
            self.assertFalse(calls.exists())
            self.assertIn("this packet is bound to", answer.stderr)
        else:
            # Reaching the engine proves held bytes and imported package origins
            # passed in the child, using only the emitted PYTHONPATH.
            self.assertEqual(json.loads(calls.read_text()), ["image", "inspect", packet["worker_image"]["reference"]])
            self.assertIn("engine answered no document", answer.stderr)

    def test_literal_start_imports_bound_runtime_before_engine_refusal(self):
        self.run_generated_start()

    def test_literal_start_refuses_source_drift_without_engine_or_store_effects(self):
        self.run_generated_start(drift=True)

    def test_literal_status_reads_the_retained_fresh_job(self):
        import subprocess
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["state"], "settled")
        _docs, places = self.generate()
        commands = json.loads(Path(places["commands.json"]).read_text())
        environment = dict(os.environ, **commands["environment"])
        empty_bin = Path(self.root) / "no-external-executables"
        empty_bin.mkdir()
        environment["PATH"] = str(empty_bin)
        answer = subprocess.run(commands["status"], env=environment, cwd=self.root, capture_output=True, text=True, timeout=20)
        self.assertEqual(answer.returncode, 0, answer.stderr)
        observed = json.loads(answer.stdout)
        self.assertEqual([job["job_id"] for job in observed["jobs"]], [packet["submission"]["job_id"]])
        self.assertEqual(len(observed["jobs"][0]["stages"]), 1)
        self.assertNotIn("Traceback", answer.stderr)


# This executable is a deterministic external engine, not an alternate supervisor.
# Unknown commands fail closed; there is no invocation of a real Docker binary.
OS_ENGINE_FIXTURE = r'''
import json, os, signal, subprocess, sys, time, traceback
from pathlib import Path
root = Path(os.environ["BATON_TEST_ENGINE_ROOT"])
state_path = root / "state.json"
done = root / "worker-done.json"
args = sys.argv[1:]
if args == ["fixture-worker"]:
    state = json.loads(state_path.read_text())
    mounts = {one["Destination"]: one["Source"] for one in state["Mounts"]}
    sys.path.insert(0, os.environ["BATON_TEST_WORKER_SOURCE"])
    sys.path.insert(0, os.environ["BATON_TEST_PROFILE_SOURCE"])
    import baton_worker, claude_agent
    baton_worker.INPUT_ROOT = claude_agent.INPUT_ROOT = mounts["/input"]
    baton_worker.OUTPUT_ROOT = claude_agent.OUTPUT_ROOT = mounts["/output"]
    credentials = root / "worker-credentials"
    credentials.mkdir()
    for target, source in mounts.items():
        if target.startswith("/run/baton/credentials/"):
            (credentials / target.rsplit("/", 1)[1]).symlink_to(source)
    claude_agent.CREDENTIAL_ROOT = str(credentials)
    (root / "worker-home").mkdir()
    calls = []
    def provider(argv, **options):
        if argv[0] == claude_agent.PROVIDER_PROGRAM:
            calls.append(list(argv))
            (root / "worker-active.json").write_text(json.dumps({"pid": os.getpid()}))
            if os.environ.get("BATON_TEST_MODE") in ("interrupt", "deadline"):
                while True:
                    time.sleep(0.02)
            selected = os.environ.get("BATON_TEST_PROVIDER_EDITS")
            edits = json.loads(Path(selected).read_text()) if selected else {"harness.py": "print('READY')\n"}
            for name, body in edits.items():
                target = Path(options["cwd"]) / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(body)
            return subprocess.CompletedProcess(argv, 0, None, None)
        return subprocess.run(argv, **options)
    code = 1
    try:
        seen = baton_worker.launched(baton_worker.read_launch(mounts["/run/baton/launch.json"]))
        code = baton_worker.serve_exchange(claude_agent.ClaudeAgent(run=provider, home=str(root / "worker-home")), seen, seen["session"], mounts["/run/baton/exchange/command"], mounts["/run/baton/exchange/events"])
    except BaseException:
        traceback.print_exc()
    finally:
        if os.environ.get("BATON_TEST_MODE") == "inaccessible" and code == 0:
            Path(mounts["/output"]).chmod(0)
        done.write_text(json.dumps({"exit_code": code, "provider_calls": len(calls)}))
    raise SystemExit(code)
with (root / "calls.jsonl").open("a") as out:
    out.write(json.dumps(args) + "\n")
if args[:2] == ["image", "inspect"]:
    print(json.dumps([{"Id": os.environ["BATON_TEST_IMAGE"]}]))
    raise SystemExit(0)
state = json.loads(state_path.read_text()) if state_path.exists() else None
def exited():
    if not state or not state.get("pid"):
        return False
    stat = Path("/proc") / str(state["pid"]) / "stat"
    return not stat.exists() or stat.read_text().split(")", 1)[1].split()[0] == "Z"
if args[0] == "create":
    assert state is None, "second container creation forbidden"
    labels, mounts = {}, []
    for i, value in enumerate(args[:-1]):
        if value == "--label":
            key, item = args[i + 1].split("=", 1)
            labels[key] = item
        if value == "--mount":
            parts = dict(p.split("=", 1) for p in args[i + 1].split(",") if "=" in p)
            mounts.append({"Source": parts["source"], "Destination": parts["target"], "RW": parts["readonly"] == "false"})
    state = {"Id": "runtime-os-fixture-1", "Image": args[-1], "Labels": labels, "Mounts": mounts, "State": {"Running": False}, "started": False}
    state_path.write_text(json.dumps(state))
    print(state["Id"])
elif args[0] == "start":
    assert state and args[-1] == state["Id"] and not state["started"]
    state["started"] = True
    state["State"]["Running"] = True
    state_path.write_text(json.dumps(state))
    with (root / "worker.log").open("wb") as log:
        child = subprocess.Popen([sys.executable, "-B", __file__, "fixture-worker"], stdin=subprocess.DEVNULL, stdout=log, stderr=log, start_new_session=True)
    state["pid"] = child.pid
    state_path.write_text(json.dumps(state))
elif args[0] == "ps":
    if state:
        print(json.dumps({"ID": state["Id"], "Image": state["Image"], "Labels": state["Labels"]}))
elif args[0] == "inspect":
    if not state or args[-1] != state["Id"]:
        print("Error response from daemon: No such container: " + args[-1], file=sys.stderr)
        raise SystemExit(1)
    if exited():
        state["State"] = {"Running": False}
        if done.exists():
            state["State"]["ExitCode"] = json.loads(done.read_text())["exit_code"]
    print(json.dumps(state))
elif args[0] == "stop":
    assert state and args[-1] == state["Id"]
    if not exited():
        os.killpg(state["pid"], signal.SIGTERM)
        deadline = time.monotonic() + 3
        while not exited() and time.monotonic() < deadline:
            time.sleep(0.01)
    assert exited(), "worker did not exit after stop"
    (root / "cessation.json").write_text(json.dumps({"pid": state["pid"], "observed": "process-exited"}))
elif args[0] == "rm":
    assert exited(), "fixture refuses removal before worker completion"
    state_path.unlink()
else:
    raise RuntimeError("unimplemented engine command: " + repr(args))
'''


class TheFreshLiteralJob(TheFreshCommandsInSubprocesses):
    def setUp(self):
        self.RUN = "fresh-os-" + self._testMethodName.removeprefix("test_literal_")
        super().setUp()

    def selections(self):
        selected = super().selections()
        secret = Path(self.root) / "fake-bearer"
        registry = Path(self.root) / "fake-credential-sources.json"
        secret.write_text("not-a-real-credential\n")
        registry.write_text(json.dumps({"schema": "baton.user-credential-sources/1", "sources": [{"provider": "fixture", "reference": "fixture/one", "path": str(secret)}]}))
        secret.chmod(0o600)
        registry.chmod(0o600)
        selected["credential_sources"] = str(registry)
        selected["credential_profile"] = {"claude": {"provider": "fixture", "reference": "fixture/one"}}
        return selected

    def run_literal_job(self, mode="positive"):
        import signal
        import time
        import subprocess
        import sys
        _docs, places = self.generate()
        commands = json.loads(Path(places["commands.json"]).read_text())
        packet = json.loads(Path(places["PACKET.json"]).read_text())
        if mode != "positive":
            packet["bounds"].update(total_seconds=12, cleanup_seconds=5)
            Path(places["PACKET.json"]).write_text(json.dumps(packet))
        root = Path(self.root) / "external-engine"
        root.mkdir()
        bindir = root / "bin"
        bindir.mkdir()
        executable = bindir / "docker"
        executable.write_text("#!" + sys.executable + "\n" + OS_ENGINE_FIXTURE)
        executable.chmod(0o700)
        (bindir / "git").symlink_to("/usr/bin/git")
        (bindir / "python3").symlink_to(sys.executable)
        environment = dict(os.environ, **commands["environment"])
        environment.update(PATH=str(bindir), BATON_TEST_MODE=mode, BATON_TEST_ENGINE_ROOT=str(root), BATON_TEST_WORKER_SOURCE=str(Path(CHECKOUT) / "v12/worker"), BATON_TEST_IMAGE=packet["worker_image"]["config_digest"], BATON_TEST_PROFILE_SOURCE=str(Path(packet["manager_source"]["path"]) / "src/baton_v12"))
        if hasattr(self, "provider_edits"):
            edit_path = root / "provider-edits.json"
            edit_path.write_text(json.dumps(self.provider_edits))
            environment["BATON_TEST_PROVIDER_EDITS"] = str(edit_path)
        try:
            with subprocess.Popen(commands["start"], env=environment, cwd=self.root, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) as supervisor:
                try:
                    if mode == "interrupt":
                        limit = time.monotonic() + 10
                        while not (root / "worker-active.json").exists() and supervisor.poll() is None and time.monotonic() < limit:
                            time.sleep(0.02)
                        self.assertTrue((root / "worker-active.json").exists(), "worker never reached provider")
                        supervisor.send_signal(signal.SIGINT)
                    stdout, stderr = supervisor.communicate(timeout=25)
                    answer = subprocess.CompletedProcess(commands["start"], supervisor.returncode, stdout, stderr)
                finally:
                    if supervisor.poll() is None:
                        supervisor.kill()
                        supervisor.communicate()
        finally:
            # This fixture owns this exact worker process group; never leave a
            # provider behind when the supervisor or an assertion fails.
            state_path = root / "state.json"
            if state_path.exists():
                state = json.loads(state_path.read_text())
                if state.get("pid"):
                    import signal
                    proc = Path("/proc") / str(state["pid"])
                    if proc.exists() and proc.joinpath("stat").read_text().split(")", 1)[1].split()[0] != "Z":
                        self.assertIn(str(executable).encode(), proc.joinpath("cmdline").read_bytes())
                        try:
                            os.killpg(state["pid"], signal.SIGKILL)
                        except ProcessLookupError:
                            pass
        diagnostic = answer.stderr + (root / "worker.log").read_text() if (root / "worker.log").exists() else answer.stderr
        self.assertEqual(answer.returncode, 130 if mode == "interrupt" else 0 if mode == "positive" else 1, diagnostic)
        outcome = json.loads(Path(commands["outcome"]).read_text())
        self.assertEqual(outcome["job_id"], packet["submission"]["job_id"])
        self.assertEqual(outcome["admitted_attempts"], outcome["workload"]["implementation_attempts"])
        self.assertEqual(len(outcome["admitted_attempts"]), 1)
        calls = [json.loads(line) for line in (root / "calls.jsonl").read_text().splitlines()]
        self.assertEqual(sum(call[0] == "create" for call in calls), 1)
        self.assertEqual(sum(call[0] == "start" for call in calls), 1)
        self.assertFalse(any(call[0] == "run" or "--entrypoint" in call for call in calls))
        observed = subprocess.run(commands["status"], env=environment, cwd=self.root, capture_output=True, text=True, timeout=20)
        self.assertEqual(observed.returncode, 0, observed.stderr)
        status = json.loads(observed.stdout)
        self.assertEqual([job["job_id"] for job in status["jobs"]], [packet["submission"]["job_id"]])
        self.assertEqual(len(status["jobs"][0]["stages"]), 1)
        self.assertEqual(status["jobs"][0]["stages"][0]["attempt_id"], outcome["admitted_attempts"][0])
        self.assertEqual(len(status["jobs"][0]["stages"][0]["episodes"]), 1)
        from baton_v12.worker_manager import ControlStore, provider_context
        with ControlStore.open(packet["deployment"]["control_store"], incarnation=self.RUN + "-context-read", clock=lambda: fixtures.NOW) as control:
            self.assertIsNone(provider_context.context_invocation_of(control, outcome["admitted_attempts"][0]))
        retained = os.environ.get("BATON_TEST_EVIDENCE_ROOT")
        if retained:
            destination = Path(retained) / (getattr(self, "evidence_prefix", "") + mode + ".json")
            destination.parent.mkdir(parents=True, exist_ok=True)
            self.assertFalse(destination.exists(), "never overwrite a retained rehearsal")
            state_path = root / "state.json"
            state = json.loads(state_path.read_text()) if state_path.exists() else None
            output = next((m["Source"] for m in state["Mounts"] if m["Destination"] == "/output"), None) if state else None
            destination.write_text(json.dumps({"mode": mode, "packet": packet, "commands": commands, "outcome": outcome, "status": status, "engine_calls": calls, "supervisor_exit": answer.returncode, "supervisor_stderr": answer.stderr, "worker_log": (root / "worker.log").read_text(), "worker_done": json.loads((root / "worker-done.json").read_text()) if (root / "worker-done.json").exists() else None, "cessation": json.loads((root / "cessation.json").read_text()) if (root / "cessation.json").exists() else None, "output_path": output, "output_mode_before_fixture_teardown": oct(Path(output).stat().st_mode & 0o777) if output else None}, indent=2) + "\n")
        if mode != "positive":
            self.assertEqual(outcome["admissions"], {"implementation": 1})
            self.assertNotEqual(outcome["state"], "settled")
            self.assertEqual(len(outcome["admitted_attempts"]), 1)
            self.assertEqual(outcome["workload"]["modes"], [])
            if mode in ("interrupt", "deadline"):
                self.assertTrue((root / "worker-active.json").exists())
                self.assertTrue((root / "cessation.json").exists(), diagnostic)
                # Cessation is proved independently, but a killed provider has
                # no retained result/committed cleanup. The supervisor must
                # preserve that exact unresolved hold rather than call it clean.
                self.assertEqual(outcome["outstanding_cleanup"], outcome["admitted_attempts"], diagnostic)
                self.assertIn("no committed cleanup", json.dumps(outcome["cleanup"]))
                self.assertIn("quiescent", json.dumps(outcome["cancellation"]))
                if mode == "deadline":
                    self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
                else:
                    self.assertTrue(outcome["interruptions"])
            else:
                state = json.loads((root / "state.json").read_text())
                output = Path(next(m["Source"] for m in state["Mounts"] if m["Destination"] == "/output"))
                self.assertTrue(output.exists())
                self.assertEqual(output.stat().st_mode & 0o777, 0)
                try:
                    self.assertIn("Permission", observed.stdout, observed.stdout)
                finally:
                    output.chmod(0o700)  # fixture-owned teardown only, after preservation evidence
            return outcome

        self.assertEqual(outcome["state"], "settled")
        self.assertEqual(outcome["admissions"], {"implementation": 1})
        self.assertEqual([proposal["attempt_id"] for proposal in outcome["workload"]["proposals"]], outcome["admitted_attempts"])
        self.assertEqual(outcome["workload"]["modes"], [])
        self.assertEqual(outcome["workload"]["shortfalls"], [])
        self.assertEqual(outcome["outstanding_cleanup"], [])
        calls = [json.loads(line) for line in (root / "calls.jsonl").read_text().splitlines()]
        self.assertEqual(sum(call[0] == "create" for call in calls), 1)
        self.assertEqual(sum(call[0] == "start" for call in calls), 1)
        self.assertFalse(any(call[0] == "run" or "--entrypoint" in call for call in calls))
        self.assertEqual(json.loads((root / "worker-done.json").read_text()), {"exit_code": 0, "provider_calls": 1})
        observed = subprocess.run(commands["status"], env=environment, cwd=self.root, capture_output=True, text=True, timeout=20)
        self.assertEqual(observed.returncode, 0, observed.stderr)
        self.assertEqual([job["job_id"] for job in json.loads(observed.stdout)["jobs"]], [packet["submission"]["job_id"]])

        return {"outcome": outcome, "status": status, "documents": _docs, "places": places}

    def test_literal_start_produces_one_fresh_proposal(self):
        self.run_literal_job()

    def test_literal_interrupt_stops_an_active_worker(self):
        self.run_literal_job("interrupt")

    def test_literal_deadline_stops_an_active_worker(self):
        self.run_literal_job("deadline")

    def test_literal_inaccessible_output_is_preserved(self):
        self.run_literal_job("inaccessible")


class TheUsefulDocumentationPacket(TheFreshLiteralJob):
    evidence_prefix = "useful-"
    DOSSIER = Path(CHECKOUT) / "work/records/2026/09/finding-v12-startup-failure-fresh-packet"
    INPUT_NAMES = ("TASK-SINGLE-JOB-20260928.md", "SOURCE-EXCERPTS-20260928.md")

    def generate(self):
        if not getattr(self, "documentation_source_ready", False):
            from baton_v12.authority import Authority
            inputs = json.loads((self.DOSSIER / "INPUTS-20260928.json").read_text())
            for name in self.INPUT_NAMES:
                source = self.DOSSIER / name
                self.assertEqual(self.digest_of(source), inputs["files"][name]["sha256"])
                Path(self.source, name).write_bytes(source.read_bytes())
            # Only the existing disposable fixture repository is committed.
            self.vcs("add", "--", *self.INPUT_NAMES)
            self.vcs("commit", "-q", "--message", "immutable documentation task inputs")
            self.base = self.vcs("rev-parse", "HEAD").strip()
            with Authority.open(self.authority_path, expected_authority_uuid=self.config["authority_uuid"]) as authority:
                authority.set_policy("canonical_target", self.base)
            self.provider_edits = {"docs/v12-first-job-inspection.md": (self.DOSSIER / "REPLAY-NOTE-299768.md").read_text()}
            self.documentation_source_ready = True
        return super().generate()

    def selections(self):
        selected = super().selections()
        image_record = json.loads((HERE / "IMAGE-ARTIFACT-244216.json").read_text())
        # Bind the documented historical image operand; the fake engine still
        # cannot establish availability, OCI access or provider behavior.
        selected["image_reference"] = image_record["reference"]
        selected["image_digest"] = image_record["image_config_digest"]
        selected["participants"]["worker_files"] = image_record["all_worker_files"]
        selected["task_instructions"] = (self.DOSSIER / self.INPUT_NAMES[0]).read_text()
        selected["verification"] = ["python3", "-c", "from pathlib import Path; p=Path('docs/v12-first-job-inspection.md'); assert p.is_file(); assert len(p.read_text().splitlines()) < 100"]
        selected["participants"]["fixture_files"] = {name: self.digest_of(Path(self.source) / name) for name in (*self.INPUT_NAMES, "harness.py")}
        return selected

    def test_literal_useful_documentation_packet(self):
        from urllib.parse import urlparse, unquote
        answer = self.run_literal_job()
        documents = answer["documents"]
        self.assertEqual(documents["task.json"]["instructions"], (self.DOSSIER / self.INPUT_NAMES[0]).read_text())
        stage = answer["status"]["jobs"][0]["stages"][0]
        self.assertEqual([a["output_name"] for a in stage["artifacts"]], ["proposal"])
        proposal = Path(unquote(urlparse(stage["artifacts"][0]["locator"]).path))
        change = answer["outcome"]["workload"]["proposals"][0]
        # Read the actual worker-produced bundle in a disposable inspection repo.
        inspection = Path(self.root) / "proposal-inspection"
        inspection.mkdir()
        self.vcs_at(str(inspection), "init", "-q")
        self.vcs_at(str(inspection), "fetch", "-q", self.source, change["base"])
        self.vcs_at(str(inspection), "fetch", "-q", str(proposal / "objects.bundle"), change["head"])
        changed = self.vcs_at(str(inspection), "diff", "--name-only", change["base"], change["head"]).splitlines()
        self.assertEqual(changed, ["docs/v12-first-job-inspection.md"])
        note = self.vcs_at(str(inspection), "show", change["head"] + ":docs/v12-first-job-inspection.md")
        self.assertEqual(note, self.provider_edits["docs/v12-first-job-inspection.md"])
        self.assertLess(len(note.splitlines()), 100)
        retained = os.environ.get("BATON_TEST_EVIDENCE_ROOT")
        if retained:
            import shutil
            destination = Path(retained) / "useful-task"
            destination.mkdir()
            for name, path in answer["places"].items():
                shutil.copyfile(path, destination / name)
            shutil.copytree(proposal, destination / "proposal")
            self.vcs("bundle", "create", str(destination / "source-base.bundle"), "HEAD")
            for name in self.INPUT_NAMES:
                shutil.copyfile(self.DOSSIER / name, destination / name)
            (destination / "verification.json").write_text(json.dumps({"base": change["base"], "head": change["head"], "changed_paths": changed, "proposal_attempt": change["attempt_id"], "job_id": answer["outcome"]["job_id"], "note_lines": len(note.splitlines()), "provider": "deterministic replay; not independent model output or acceptance"}, indent=2) + "\n")


def load_tests(loader, tests, pattern):
    """THIS FILE'S OWN CHECKS, and not the ones it inherits.

    The composition cases extend `BaselineCase`, which extends
    `ManagedSessionResume`; running those inherited methods again here would
    re-attribute other files' measured evidence to this one.
    """
    del tests, pattern, loader
    suite = unittest.TestSuite()
    for case in (TheGeneratedPacketDrivesOneImplementation,
                 TheCompositionCarriesOnlyThisJobsWorkload,
                 TheComposerRefusesWhatItCannotHold, TheFreshPacket,
                 TheFreshCommandsInSubprocesses, TheFreshLiteralJob,
                 TheUsefulDocumentationPacket):
        for name in sorted(one for one in vars(case)
                           if one.startswith("test")):
            suite.addTest(case(name))
    return suite
