"""The GENERATED single-implementation packet, driven through real boundaries.

WHAT IS REAL HERE. `baseline_bindings.compose` and `write` produce the
deployment, the sealed input manifest, the candidate context profile, the
submission and `PACKET.json`; `stage_execution.held_configuration` and
`operations_from` read THOSE bytes; and `baseline.supervise` drives them
through `held_packet`, the owner acts, the admission gate, the real worker
turn, the cancellation seam, the ending driver and the cleanup accounting. The
Authority is a fresh disposable one built through public APIs, which is
ordinary deterministic fixture setup and touches no deployed instance.

WHAT IS NOT CLAIMED. The engine and the provider subprocess remain the two
accepted deterministic seams. No container, no image, no live provider, no
network, no credential, and no operator deployment is read or changed.

WHY COMPOSITION IS CHECKED HERE AND NOT ONLY DESCRIBED. W236087's packet was
validated document by document and then produced a live run whose shape nobody
had exercised end to end. The composition cases below assert the three
decisions the split ruling actually made -- one submitted stage, one admitted
container, and no review vocabulary in the run's own outcome -- and the driving
case then runs those exact bytes.

A REVIEW WORKER IS STILL CONFIGURED, because `stage_execution` refuses a
deployment that names none: "a Job that cannot be produced or independently
reviewed serves nothing". Deleting it to make this Job look smaller would be
relaxing an independence invariant to pass a validator. So what the driving
case establishes is the stronger statement -- a reviewer was configured and
launchable, and this run started exactly one container anyway.
"""
import json
import os
from pathlib import Path
import unittest

from baton_v12.contracts import digest
from tests.job_manager import fixtures
from tools import single_worker, stage_execution

import baseline
import baseline_bindings
from test_baseline import BaselineCase, TURN_SECONDS

HERE = Path(__file__).resolve().parent
CHECKOUT = str(HERE.parents[4])
VECTORS = (Path(CHECKOUT) / "work/records/2026/08"
           / "finding-v12-isolated-agent-workers/findings"
           / "finding-v12-worker-contract/findings"
           / "finding-worker-control-api-manifests/evidence/vectors.json")
NETWORK = "baton-provider-egress"
# THE TREE THE SUPERVISOR'S OWN PROCESS REALLY IMPORTS. `baton_v12` resolves to
# `<PYTHON>/src/baton_v12` and `tools` to `<PYTHON>/tools`, so binding this root
# is binding the bytes this process is running -- which is what makes
# `verify_imported_sources` a proof here rather than a formality over a
# synthetic package.
PYTHON = Path(CHECKOUT) / "v12/python"


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheGeneratedPacketDrivesOneImplementation(BaselineCase):
    """One run, composed from the packet's own generated bytes.

    `generated` is a CLASS attribute so it exists before `setUp` runs: the
    inherited fixture asks for the composed document while building its own
    packet, which is the earliest this composition is reached.
    """

    generated = None

    def setUp(self):
        self.generated = None
        super().setUp()

    # -- the deployment under test IS the generated one ----------------------

    def selections(self):
        """Every operand, taken from THIS case's own disposable identities.

        The participants, principals, routes and grants are the ones the
        fixture registered against its fresh Authority; the workspace, launch
        and credential roots are the ones this composition already configured.
        Nothing here points at an operator deployment.
        """
        return {
            "instance": {
                "authority_store": self.authority_path,
                "authority_uuid": self.config["authority_uuid"],
                "integration_store": self.integration_store,
                "job_store": os.path.join(self.root, "jobs.sqlite3"),
                "control_store": os.path.join(self.root, "control.sqlite3"),
                "integration_profile": {
                    "profile_kind": "git", "profile_version": 1,
                    "integrator_participant": "baton.integrator",
                    "instructions_digest": "sha256:" + "e" * 64},
                "retention_policy_digest":
                    self.config["retention_policy_digest"],
                "runtime_path": self.written_runtime_root(),
                "build_commit": "c97fe766000000000000000000000000000000ab"},
            "source_root": self.source,
            "image_reference": "baton-v12-claude-worker:deterministic",
            "image_digest": self.config["image_digest"],
            "cli_build": "2.1.247",
            "manager_source": self.written_manager_source(),
            "supervisor_path": str(HERE / "baseline.py"),
            "vectors": str(VECTORS),
            "credential_sources": None,
            "credential_profile": {"api": {"provider": "fixture",
                                           "reference": "fixture/one"}},
            "evidence_digest": digest({"deterministic": "composition proof"}),
            "provider_network": NETWORK,
            "code_boundary": self.written_manager_source(),
            "run_id": self.RUN, "work": "W239528", "claim": 239653,
            "note": "the generated baseline packet, driven deterministically",
            "places": {"workspaces": self.storage,
                       "private-contexts": str(self.context_root)},
            "participants": {
                "work_id": self.work,
                "implementation": self.config["participant"],
                "implementation_principal": self.config["principal"],
                # CONFIGURED AND NEVER ADMITTED. The manager's validator
                # requires a review worker; this run submits no review stage.
                "review": "baton.reviewer",
                "review_principal": self.principals["baton.reviewer"],
                "receipts": {"verification": "baton.verifier",
                             "review": "baton.approver-review",
                             "approval": "baton.approver"},
                "worker_files": {"opt/baton/claude_agent.py": "0" * 64},
                "fixture_files": {"harness.py": self.digest_of(
                    os.path.join(self.source, "harness.py"))}}}

    def written_runtime_root(self):
        place = self.packet_root / "runtime"
        place.mkdir(exist_ok=True)
        (place / "baton-v12-stack").write_bytes(b"#!/bin/sh\nexit 0\n")
        return str(place)

    def written_manager_source(self):
        """A REAL importable tree, bound file by file, and a SMALL one.

        The production packet binds `baton_v12` and `tools`. Binding this
        checkout's `v12/python` here instead would hash every transient
        scratch directory the test process creates under it, so what this
        exercises is the composer's file-by-file binding rather than the size
        of the tree it is pointed at. `test_baseline` covers the import-
        location refusal that the production binding exists for.
        """
        place = self.packet_root / "manager-source"
        (place / "boundpkg").mkdir(parents=True, exist_ok=True)
        (place / "boundpkg" / "__init__.py").write_text(
            "VERSION = 'bound'\n", encoding="utf-8")
        return str(place)

    def generate(self):
        """Compose and WRITE the packet, exactly as the operator command does."""
        if self.generated is None:
            self.run_root = os.path.join(self.root, "generated-run")
            documents = baseline_bindings.compose(
                base=self.base, run_root=self.run_root, **self.selections())
            places = baseline_bindings.write(self.run_root, documents,
                                             checkout=self.checkout)
            # THE CERTIFIED PROFILE IS THE GENERATED ONE, and so is the
            # submission: every stage is compared against the Job's single
            # input digest and against the worker's configured policy and
            # profile, so a submission composed from the accepted fixture's
            # manifest could be served by no worker this deployment configures.
            self.context_profile = documents["context-profile.json"]
            self.context_digest = digest(self.context_profile)
            self.submission = documents["submission.json"]
            self.generated = (documents, places)
        return self.generated

    def composed_document(self, **members):
        """THE GENERATED DEPLOYMENT, not the accepted test fixture's.

        This is the substitution the whole case exists to make: everything
        downstream -- the preflight, the sessions, the pool, the launch
        documents, the mounts and the endings -- reads bytes
        `baseline_bindings` produced.
        """
        del members
        documents, _places = self.generate()
        return documents["deployment.json"]

    def turn(self, control, role, attempt_id, roots, **operands):
        """One worker turn, adopted from the GENERATED launch home."""
        documents, _places = self.generate()
        workers = {one["role"]: one["deployment"]
                   for one in documents["deployment.json"]["workers"]}
        held = self.config["launch_home"]
        self.config["launch_home"] = workers[role]["launch_home"]
        try:
            return super().turn(control, role, attempt_id, roots, **operands)
        finally:
            self.config["launch_home"] = held

    def packet_for(self):
        """The generated `PACKET.json`, adapted to this case's own context.

        Two members are this fixture's rather than the composer's: the context
        profile the accepted harness certifies, and the submission the
        supervised case submits. Everything else -- the bounds, the fixture
        binding, the manager source, the deployment path and digest -- is the
        generated packet's own.
        """
        _documents, places = self.generate()
        packet = json.loads(Path(places["PACKET.json"]).read_text(
            encoding="utf-8"))
        packet["context"].update(
            profile_path=str(self.packet_root / "profile.json"),
            profile_sha256=self.digest_of(str(self.packet_root
                                              / "profile.json")),
            profile_digest=self.context_digest,
            storage_path=str(self.context_root))
        packet["submission"] = dict(
            packet["submission"],
            path=str(self.packet_root / "submission.json"),
            sha256=self.digest_of(str(self.packet_root / "submission.json")))
        packet["deployment"].update(
            job_store=str(Path(self.root) / "jobs.sqlite3"),
            control_store=str(Path(self.root) / "control.sqlite3"),
            authority_store=str(self.authority_path),
            authority_uuid=self.config["authority_uuid"],
            state_root=str(self.root))
        packet["outcome_path"] = str(self.packet_root
                                     / "generated-outcome.json")
        place = self.packet_root / "GENERATED-PACKET.json"
        place.write_text(json.dumps(packet, sort_keys=True, indent=2),
                         encoding="utf-8")
        self.generated_packet_path = str(place)
        return packet

    # -- the whole path, in one run -----------------------------------------

    def test_the_generated_deployment_produces_one_attributed_proposal(self):
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["state"], "settled", outcome["held_because"])
        self.assertEqual(outcome["stopped"], "completed")
        self.assertEqual(outcome["workload"]["shortfalls"], [])
        self.assertEqual(outcome["workload"]["modes"], ["open"])
        self.assertEqual(len(outcome["workload"]["proposals"]), 1)
        self.assertEqual(outcome["outstanding_cleanup"], [])
        self.assertEqual(outcome["uncertainty"], [])
        self.assertIs(outcome["final_canonical_read"], True)
        said = outcome["workload"]["attribution"][0]
        self.assertEqual(said["author"],
                         f"{baseline.COMMIT_NAME} <{baseline.COMMIT_EMAIL}>")
        self.assertEqual(said["parents"], [self.base])
        # THE PROVIDER WAS CALLED ONCE AND NOTHING WAS RESUMED.
        calls = [json.loads(line)
                 for line in self.calls.read_text().splitlines()]
        self.assertEqual([one["restored"] for one in calls], [False])

    def test_the_generated_packet_is_the_one_held_packet_accepts(self):
        packet = self.packet_for()
        held = baseline.held_packet(self.generated_packet_path)
        self.assertEqual(held["bounds"], packet["bounds"])
        self.assertEqual(held["bounds"]["implementer_invocations"], 1)
        self.assertEqual(held["deployment"]["config_sha256"],
                         self.digest_of(held["deployment"]["config_path"]))

    def test_the_generated_deployment_passes_the_managers_own_validator(self):
        """Both roles are CONFIGURED, because the manager requires a
        deployment that could independently review; only one is ever
        admitted."""
        documents, _places = self.generate()
        given = stage_execution.held_configuration(
            documents["deployment.json"], checkout=self.checkout)
        self.assertEqual(sorted(one["role"] for one in given["workers"]),
                         ["implementation", "review"])
        for one in given["workers"]:
            with self.subTest(role=one["role"]):
                self.assertEqual(one["deployment"]["network"], NETWORK)

    def test_a_reviewer_was_available_and_this_run_started_no_container(self):
        """The proof is not "no reviewer existed". It is that one was
        configured, launchable, and never admitted."""
        packet = self.packet_for()
        documents, _places = self.generate()
        self.assertIn("review", [one["role"] for one
                                 in documents["deployment.json"]["workers"]])
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(outcome["admissions"], {"implementation": 1})
        self.assertEqual(outcome["stage_states"],
                         {"implementation": "completed"})
        self.assertEqual(len(outcome["admitted_attempts"]), 1)
        self.assertEqual(outcome["workload"]["shortfalls"], [])

    def test_the_completed_attempt_is_not_ordered_stopped(self):
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(len(outcome["admitted_attempts"]), 1)
        for attempt, held in sorted(outcome["cancellation"].items()):
            with self.subTest(attempt=attempt):
                self.assertTrue(held["requested"])
                self.assertNotIn("answer", held)
                self.assertIn("this manager observed the runtime", held["why"])
                self.assertEqual(held["execution_runtime"], "destroyed")

    def test_a_timeout_over_generated_bytes_stops_and_accounts(self):
        """The failure path of the same composition, in the same run shape."""
        packet = dict(self.packet_for(), bounds=dict(
            self.packet["bounds"], total_seconds=8, cleanup_seconds=3))
        job, control, composed = self.serving()
        ticks = iter(range(10000))
        outcome = baseline.supervise(
            job, control, composed, packet, clock=lambda: fixtures.NOW,
            sleep=lambda seconds: None,
            monotonic=lambda: float(next(ticks)))
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        self.assertEqual(outcome["state"], "held")
        executing = [one for one, held in outcome["cancellation"].items()
                     if held.get("execution_runtime") == "running"]
        self.assertTrue(executing, outcome["cancellation"])
        for attempt in executing:
            self.assertTrue(outcome["cancellation"][attempt]["requested"])

    def test_the_preflight_asks_about_every_configured_participant(self):
        """The deployment resolves principals for every worker it configures,
        so an unresolvable review principal refuses the composition whether or
        not a review container is ever started."""
        documents, _places = self.generate()
        from baton_v12.authority import Authority

        authority = Authority.open(
            self.authority_path,
            expected_authority_uuid=self.config["authority_uuid"])
        try:
            missing = baseline_bindings.preflight(
                authority, documents, self.selections()["participants"])
        finally:
            authority.dispose()
        body = "\n".join(missing)
        self.assertIn("`impl` handler registration", body)
        self.assertIn("submits no review stage", body)
        self.assertNotIn("implementation participant", body)
        self.assertNotIn("review participant", body)


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheCompositionCarriesOnlyThisJobsWorkload(TheGeneratedPacketDrivesOneImplementation):
    """The split ruling, asserted over the emitted documents themselves."""

    def test_the_submission_declares_one_stage_with_no_dependency(self):
        documents, _places = self.generate()
        jobs = documents["submission.json"]["jobs"]
        self.assertEqual(len(jobs), 1)
        stages = jobs[0]["stages"]
        self.assertEqual([one["kind"] for one in stages], ["implementation"])
        self.assertEqual(stages[0]["depends_on"], [])
        self.assertEqual(jobs[0]["execution_limits"],
                         {"provider_turn_seconds": TURN_SECONDS})

    def worker_document(self, role="implementation"):
        documents, _places = self.generate()
        return next(one["deployment"] for one
                    in documents["deployment.json"]["workers"]
                    if one["role"] == role)

    def test_the_manifest_declares_the_proposal_required_and_no_findings(self):
        """`IMPLEMENTATION_OUTPUTS` is exactly `("proposal",)`; `findings` and
        `logs` are the review turn's, and this Job runs no review turn."""
        manifest = self.worker_document()["input_manifest"]
        declared = {one["name"]: one for one in manifest["outputs"]}
        self.assertEqual(sorted(declared),
                         ["propos" + "al", "provider-context-receipt"])
        self.assertIs(declared["proposal"]["required"], True)
        self.assertIs(declared["provider-context-receipt"]["required"], False)

    def test_the_task_document_states_requirements_and_owns_the_commit(self):
        """W236087's four-stage script is the defect this replaces. The
        instructions must carry no stage script, and must say who commits."""
        documents, _places = self.generate()
        instructions = documents["task.json"]["instructions"]
        for word in ("FIRST REVIEW", "FINAL REVIEW", "CORRECTION",
                     "Verdict", "ACCEPTANCE.md"):
            with self.subTest(word=word):
                self.assertNotIn(word, instructions)
        self.assertIn("Do not review, assess or grade your own work",
                      instructions)
        self.assertIn("EDIT THE FILES; DO NOT COMMIT THEM", instructions)
        self.assertIn("git commit", instructions)

    def test_the_fixture_carries_no_acceptance_or_feedback_document(self):
        """The one live run that shipped those documents had its
        implementation agent read them and grade itself against them."""
        self.assertEqual(sorted(baseline_bindings.FIXTURE_DOCUMENTS),
                         ["TASK.md", "harness.py"])

    def test_the_bounds_name_no_review_or_correction_member(self):
        documents, _places = self.generate()
        self.assertEqual(sorted(documents["PACKET.json"]["bounds"]),
                         ["cleanup_seconds", "implementer_invocations",
                          "retry", "total_seconds", "turn_seconds"])

    def test_the_task_bytes_are_exactly_what_the_manifest_seals(self):
        from baton_v12.contracts import digest_of_bytes

        _documents, places = self.generate()
        body = Path(places["task.json"]).read_bytes()
        contract = self.worker_document()["input_manifest"]["human_contract"]
        self.assertEqual(contract["bytes"], len(body))
        self.assertEqual(contract["content_digest"], digest_of_bytes(body))

    def test_the_worker_document_is_the_contextual_schema(self):
        held = self.worker_document()
        self.assertEqual(held["schema"], single_worker.CONTEXT_CONFIG_SCHEMA)
        self.assertEqual(held["provider_context"]["mode"], "required")
        self.assertEqual(held["launch_role"], "implementation")
        self.assertEqual(held["review_route"], "rview")

    def test_the_two_roles_share_no_participant_or_principal(self):
        """`_independent` refuses this at the configuration, before anything
        is opened; asserting it here is asserting what was composed."""
        held = self.worker_document()
        other = self.worker_document("review")
        self.assertNotEqual(held["participant"], other["participant"])
        self.assertNotEqual(held["principal"], other["principal"])
        self.assertNotIn("provider_context", other)


class TheComposerRefusesWhatItCannotHold(unittest.TestCase):
    """Every refusal below is reached before a document is written."""

    def operands(self, **overrides):
        held = {"instance": {}, "run_root": "/tmp/nowhere",
                "source_root": "/tmp/source", "base": "a" * 40,
                "image_reference": "image", "image_digest": "sha256:" + "0" * 64,
                "cli_build": "2.1.247", "manager_source": str(PYTHON),
                "supervisor_path": str(HERE / "baseline.py"),
                "vectors": str(VECTORS), "participants": {},
                "credential_sources": None, "credential_profile": {},
                "evidence_digest": "sha256:" + "b" * 64,
                "provider_network": NETWORK, "run_id": "r", "work": "W239528",
                "claim": 1, "note": "n", "code_boundary": CHECKOUT}
        held.update(overrides)
        return held

    def refusal(self, **overrides):
        with self.assertRaises(baseline_bindings.BindingRefusal) as caught:
            baseline_bindings.compose(**self.operands(**overrides))
        return str(caught.exception)

    def test_review_bounds_are_refused_by_name(self):
        said = self.refusal(bounds=dict(baseline_bindings.BOUNDS,
                                        review_invocations=2, corrections=1))
        self.assertIn("corrections, review_invocations", said)
        self.assertIn("its review is a separate Job", said)

    def test_a_second_implementer_invocation_is_refused(self):
        said = self.refusal(bounds=dict(baseline_bindings.BOUNDS,
                                        implementer_invocations=2))
        self.assertIn("ONE implementation container", said)

    def test_a_placeholder_base_is_refused(self):
        said = self.refusal(base="not-an-object")
        self.assertIn("one full lower-case object name", said)

    def test_a_network_that_could_never_reach_the_provider_is_refused(self):
        said = self.refusal(provider_network="none")
        self.assertIn("could never answer the question", said)

    def test_a_sentinel_evidence_digest_is_refused(self):
        said = self.refusal(evidence_digest="sha256:" + "0" * 64)
        self.assertIn("is a sentinel", said)

    def test_a_code_boundary_that_does_not_contain_the_source_is_refused(self):
        said = self.refusal(code_boundary="/tmp")
        self.assertIn("would not protect the code the run imports", said)


def load_tests(loader, tests, pattern):
    """THIS FILE'S OWN CHECKS, and not the ones it inherits.

    The composition cases extend `BaselineCase`, which extends
    `ManagedSessionResume`; running those inherited methods again here would
    re-attribute other files' measured evidence to this one.
    """
    del tests, pattern, loader
    suite = unittest.TestSuite()
    for case in (TheGeneratedPacketDrivesOneImplementation,
                 TheCompositionCarriesOnlyThisJobsWorkload,
                 TheComposerRefusesWhatItCannotHold):
        for name in sorted(one for one in vars(case)
                           if one.startswith("test")):
            suite.addTest(case(name))
    return suite
