"""The two OPERATOR ENTRYPOINTS, run as documented. W239528 R1.

Review 2026-09-22T15:32:51Z: "OPERATOR-239528.md steps 3 and 5 invoke plain
`python3` without binding the interpreter, import path or working directory. In
a child with no implicit PYTHONPATH, the documented composer command fails at
its first product import with `ModuleNotFoundError: No module named
'baton_v12'`... Validate the composer and supervisor entrypoint with a
disposable, relocated real source tree and generated bytes."

That reproduction is correct and this file is the answer to it. Two things were
missing and both are here:

  * `baseline_bindings.main` had never been executed as the operator executes
    it -- a child process, with an explicit interpreter and an explicit import
    path, and nothing inherited from a developer shell. `TheDocumentedComposer`
    runs the exact command `OPERATOR-239528.md` now prints, in a child whose
    `PYTHONPATH` is set to the bound source and to nothing else, over a
    RELOCATED copy of the real `baton_v12` and `tools` -- the flattened layout
    a deployed manager source actually has, which is the layout that makes one
    `PYTHONPATH` entry sufficient.
  * `baseline.main` had never been executed at all. The composition cases call
    `supervise` directly, so `main`'s own path -- the packet proving, the
    import binding, the engine question, the Job survey, opening both stores,
    the owner acts, composing the deployment and the exit status -- was
    uncovered. `TheDocumentedSupervisor` drives it.

WHAT IS RELOCATED AND WHAT IS IMPORTED, because they are deliberately not the
same tree. The composer child imports from the relocated copy, which is what a
deployed operator does. The supervisor case runs IN THIS PROCESS, so the tree
it must bind is the one this process really imports -- `verify_imported_sources`
compares the imported packages' resolved locations against the bound source,
and binding anything else would make it pass for the wrong reason or refuse for
one. The relocated copy is therefore used a second way in the supervisor case:
as the packet a correct `main` REFUSES, before opening any store.

THE TWO DETERMINISTIC SEAMS STAY WHERE THEY ARE. `baseline.main` already takes
`compose` and `image_inspect` for a deployment to supply, and `time.sleep` is
patched because the composed deployment has no daemon to run a container. No
container, image, live provider, network, credential or deployed store is
reached.
"""
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import unittest
from unittest import mock

from tests.job_manager import fixtures
from tools import stage_execution

import baseline
import baseline_bindings
from test_baseline_bindings import (CHECKOUT, PYTHON, VECTORS,
                                    TheGeneratedPacketDrivesOneImplementation)

HERE = Path(__file__).resolve().parent
# The two packages a deployed manager source provides, and the places they live
# in THIS checkout. A relocation flattens them to the root, which is why one
# `PYTHONPATH` entry is enough for the deployed layout and two would be needed
# for this one.
RELOCATED = (("src/baton_v12", "baton_v12"), ("tools", "tools"))


def relocate(into):
    """A REAL manager source, copied into a disposable directory.

    Real bytes -- this is `shutil.copytree` over the checkout's own packages,
    not a synthetic package with one file in it. `__pycache__` is skipped for
    the reason the composer skips it: compiled artefacts are not source, and a
    tree whose digests changed every time a different interpreter imported it
    could not be pinned.
    """
    into = Path(into)
    into.mkdir(parents=True, exist_ok=True)
    for source, name in RELOCATED:
        shutil.copytree(PYTHON / source, into / name,
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    return str(into)


class EntrypointCase(TheGeneratedPacketDrivesOneImplementation):
    """The generated composition, with the real trees bound."""

    def relocated_source(self):
        if getattr(self, "_relocated", None) is None:
            self._relocated = relocate(Path(self.root) / "relocated-source")
        return self._relocated

    def imported_source(self):
        """The REAL `baton_v12` and `tools`, as this process imports them.

        `baton_v12` resolves to `<PYTHON>/src/baton_v12` and `tools` to
        `<PYTHON>/tools`, so binding `<PYTHON>` binds the bytes this process is
        running -- which is what makes `verify_imported_sources` a proof here
        rather than a formality over a tree nothing imports. Only the two
        package directories are walked: the checkout root also holds transient
        scratch directories a test process creates, and a binding that hashed
        those could never verify twice.
        """
        files = {}
        for relative, _name in RELOCATED:
            for base, dirs, names in os.walk(PYTHON / relative):
                dirs[:] = [one for one in sorted(dirs)
                           if one != "__pycache__"]
                for name in sorted(names):
                    if name.endswith(".pyc"):
                        continue
                    whole = os.path.join(base, name)
                    files[os.path.relpath(whole, PYTHON)] = \
                        self.digest_of(whole)
        return {"path": str(PYTHON), "packages": ["baton_v12", "tools"],
                "file_count": len(files), "files": files}


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheDocumentedComposerRunsAsDocumented(EntrypointCase):
    """Step 3 of the operator document, executed as a child process."""

    def written_selections(self, **overrides):
        """The selections file the operator edits, with this case's operands.

        Every value is this fixture's own disposable identity. Nothing here
        points at a deployed instance, and the composer opens no store.
        """
        held = self.selections()
        held["manager_source"] = self.relocated_source()
        held["code_boundary"] = self.relocated_source()
        held["run_id"] = self.RUN + "-entrypoint"
        held.update(overrides)
        place = Path(self.root) / "entrypoint-selections.json"
        place.write_text(json.dumps({"compose": held}, indent=2,
                                    sort_keys=True), encoding="utf-8")
        return str(place)

    def child(self, selections, run_root, *, bind=True):
        """The documented command, with NOTHING inherited from this shell.

        `PYTHONPATH` is removed and then set to exactly the bound source, which
        is what the operator document prints. `bind=False` removes it
        altogether, which is the reviewer's reproduction.
        """
        environment = dict(os.environ, PYTHONDONTWRITEBYTECODE="1")
        environment.pop("PYTHONPATH", None)
        if bind:
            environment["PYTHONPATH"] = self.relocated_source()
        return subprocess.run(
            [sys.executable, str(HERE / "baseline_bindings.py"),
             "--selections", selections, "--base", self.base,
             "--run-root", run_root],
            capture_output=True, text=True, timeout=300, env=environment,
            cwd=os.sep)

    def test_the_documented_command_composes_the_whole_packet(self):
        run_root = os.path.join(self.root, "entrypoint-run")
        answer = self.child(self.written_selections(), run_root)
        self.assertEqual(answer.returncode, 0,
                         f"stdout={answer.stdout}\nstderr={answer.stderr}")
        # IT PRINTS WHAT IT WROTE, and every one of them is on disk.
        printed = json.loads(answer.stdout)
        self.assertEqual(
            sorted(printed),
            ["PACKET.json", "adapter.json", "context-profile.json",
             "deployment.json", "policy.json", "runtime-profile.json",
             "submission.json", "task.json"])
        for name, digest in sorted(printed.items()):
            with self.subTest(document=name):
                place = os.path.join(run_root, name)
                self.assertTrue(os.path.exists(place), place)
                self.assertEqual(self.digest_of(place), digest)

    def test_the_command_runs_from_any_working_directory(self):
        """Every path the document prints is absolute; `cwd` is the filesystem
        root above, so nothing resolved relative to a developer's shell."""
        run_root = os.path.join(self.root, "rootcwd-run")
        answer = self.child(self.written_selections(), run_root)
        self.assertEqual(answer.returncode, 0, answer.stderr)
        self.assertTrue(os.path.exists(os.path.join(run_root, "PACKET.json")))

    def test_without_the_bound_import_path_it_fails_exactly_as_reported(self):
        """The reviewer's reproduction, kept as a regression.

        This is what the previous operator document told an operator to run. It
        fails at the first product import, before any write -- so the check
        below is BOTH that the failure is real and that it is harmless.
        """
        run_root = os.path.join(self.root, "unbound-run")
        answer = self.child(self.written_selections(), run_root, bind=False)
        self.assertNotEqual(answer.returncode, 0)
        self.assertIn("No module named 'baton_v12'", answer.stderr)
        self.assertFalse(os.path.exists(run_root),
                         "it failed before writing anything, and that is the "
                         "only reason the old command was merely unusable "
                         "rather than damaging")

    def test_the_composed_packet_is_the_one_held_packet_accepts(self):
        run_root = os.path.join(self.root, "accepted-run")
        answer = self.child(self.written_selections(), run_root)
        self.assertEqual(answer.returncode, 0, answer.stderr)
        held = baseline.held_packet(os.path.join(run_root, "PACKET.json"))
        self.assertEqual(held["manager_source"]["path"],
                         self.relocated_source())
        self.assertEqual(sorted(held["manager_source"]["packages"]),
                         ["baton_v12", "tools"])
        # A RELOCATED TREE IS FLAT, which is what makes one PYTHONPATH entry
        # enough. If this ever became `src/baton_v12/...` the documented
        # command would need a second entry and would silently be wrong.
        self.assertTrue(
            any(one.startswith("baton_v12" + os.sep)
                for one in held["manager_source"]["files"]),
            sorted(held["manager_source"]["files"])[:5])
        self.assertGreater(held["manager_source"]["file_count"], 50)

    def test_the_composed_job_identity_follows_the_run_identity(self):
        run_root = os.path.join(self.root, "identity-run")
        answer = self.child(self.written_selections(), run_root)
        self.assertEqual(answer.returncode, 0, answer.stderr)
        packet = json.loads(
            Path(run_root, "PACKET.json").read_text(encoding="utf-8"))
        self.assertEqual(packet["submission"]["job_id"],
                         "job-" + self.RUN + "-entrypoint")
        self.assertEqual(packet["context"]["job_id"],
                         packet["submission"]["job_id"])


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheDocumentedSupervisorRunsThroughMain(EntrypointCase):
    """Step 5 of the operator document, through `baseline.main` itself."""

    def main_packet(self, **overrides):
        """The generated packet, bound to the source this process imports."""
        packet = self.packet_for()
        packet["manager_source"] = self.imported_source()
        # THE CODE BOUNDARY IS `tools/`: the fixture's disk-backed roots are
        # siblings of `src/` and `tools/` rather than inside either, which is
        # the same shape a relocated manager source has beside its run root.
        packet["code_boundary"] = str(PYTHON / "tools")
        packet["deployment"] = dict(
            packet["deployment"],
            job_store=os.path.join(self.root, "main-jobs.sqlite3"),
            control_store=os.path.join(self.root, "main-control.sqlite3"))
        packet["outcome_path"] = str(self.packet_root / "main-outcome.json")
        packet.update(overrides)
        place = self.packet_root / "MAIN-PACKET.json"
        place.write_text(json.dumps(packet, sort_keys=True, indent=2),
                         encoding="utf-8")
        self.main_packet_path = str(place)
        return packet

    def composing(self, driven):
        """`main`'s composition seam, answering the accepted simulated one."""
        def compose(packet, job, control, stream):
            del packet, stream
            composed = stage_execution.operations_from(
                self.composed_document(), job, control,
                engine_run=self.engine,
                credential_provider=lambda provider, reference: self.secret,
                clock=lambda: fixtures.NOW, checkout=self.checkout)
            self._composed = composed
            self.addCleanup(composed.close)
            driven.append((job, control, composed))
            return composed
        return compose

    def run_main(self, packet, *, drive=True, incarnation="entrypoint-main"):
        """`main`, with the container boundary driven from its own wait."""
        self.engine = self.quiescing()
        driven, stream = [], io.StringIO()
        inspect = mock.Mock(return_value={
            "Id": packet["worker_image"]["config_digest"]})

        def waiting(seconds):
            del seconds
            if drive and driven:
                job, control, composed = driven[-1]
                if self.states(job, composed).get(
                        "implementation") == "waiting":
                    return self.run_implementation(control, composed)
            return None

        with mock.patch.object(baseline.time, "sleep", waiting):
            status = baseline.main(
                ["--packet", self.main_packet_path,
                 "--incarnation", incarnation],
                stream=stream, compose=self.composing(driven),
                image_inspect=inspect)
        return status, stream.getvalue(), driven

    # -- the paths through the entrypoint ------------------------------------

    def test_main_completes_one_implementation_and_exits_zero(self):
        packet = self.main_packet()
        status, said, driven = self.run_main(packet)
        self.assertEqual(status, 0, said)
        self.assertTrue(driven, "main never composed the deployment")
        outcome = json.loads(
            Path(packet["outcome_path"]).read_text(encoding="utf-8"))
        self.assertEqual(outcome["state"], "settled", outcome["held_because"])
        self.assertEqual(outcome["workload"]["shortfalls"], [])
        self.assertEqual(outcome["workload"]["modes"], ["open"])
        self.assertEqual(outcome["outstanding_cleanup"], [])
        said_by = outcome["workload"]["attribution"][0]
        self.assertEqual(said_by["author"],
                         f"{baseline.COMMIT_NAME} <{baseline.COMMIT_EMAIL}>")
        self.assertEqual(said_by["parents"], [self.base])
        # AND MAIN OPENED ITS OWN STORES, which is half of what it adds.
        self.assertTrue(os.path.exists(packet["deployment"]["job_store"]))
        self.assertTrue(os.path.exists(packet["deployment"]["control_store"]))

    def test_main_holds_and_exits_one_when_the_bound_elapses(self):
        packet = self.main_packet(bounds=dict(
            self.packet["bounds"], total_seconds=3, cleanup_seconds=2))
        status, said, _driven = self.run_main(packet, drive=False)
        self.assertEqual(status, 1, said)
        outcome = json.loads(
            Path(packet["outcome_path"]).read_text(encoding="utf-8"))
        self.assertEqual(outcome["state"], "held")
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        executing = [one for one, held in outcome["cancellation"].items()
                     if held.get("execution_runtime") == "running"]
        self.assertTrue(executing, outcome["cancellation"])
        stops = {argv[-1] for argv in self.engine.vectors if argv[1] == "stop"}
        self.assertTrue({outcome["cancellation"][one]["runtime_id"]
                         for one in executing}.issubset(stops))

    def test_main_refuses_a_source_this_process_does_not_import(self):
        """The relocated copy is REAL and is not what this process runs.

        Every digest in it verifies -- it is a byte-for-byte copy -- so this is
        exactly the case `held_packet` alone cannot catch, and exactly why
        `verify_imported_sources` exists. It refuses before a store is opened.
        """
        relocated = self.relocated_source()
        files = {}
        for base, dirs, names in os.walk(relocated):
            dirs[:] = [one for one in sorted(dirs) if one != "__pycache__"]
            for name in sorted(names):
                whole = os.path.join(base, name)
                files[os.path.relpath(whole, relocated)] = \
                    self.digest_of(whole)
        packet = self.main_packet(manager_source={
            "path": relocated, "packages": ["baton_v12", "tools"],
            "file_count": len(files), "files": files})
        status, said, driven = self.run_main(packet)
        self.assertEqual(status, 2, said)
        self.assertIn("outside the bound manager source", said)
        self.assertEqual(driven, [], "it refused before composing anything")
        self.assertFalse(os.path.exists(packet["deployment"]["job_store"]),
                         "it refused before opening a store")

    def test_main_refuses_a_job_identity_the_store_already_holds(self):
        """R2 at the entrypoint: BEFORE the owner acts, so no grant is spent.

        The first run mints this packet's one-run qualification grant and
        submits its Job. The second names the same Job identity -- which is
        what a reused Job id does, however fresh the run name is -- and must be
        refused before `prepare` commits anything a second time.
        """
        packet = self.main_packet()
        status, said, _driven = self.run_main(packet)
        self.assertEqual(status, 0, said)
        again = self.main_packet(outcome_path=str(
            self.packet_root / "second-outcome.json"))
        status, said, driven = self.run_main(
            again, drive=False, incarnation="entrypoint-main-again")
        self.assertEqual(status, 2, said)
        self.assertIn("already records", said)
        self.assertIn("no qualification grant was spent", said)
        self.assertEqual(driven, [], "it refused before composing anything")
        self.assertFalse(
            os.path.exists(again["outcome_path"]),
            "a refused run writes no outcome, so nothing reads as a result")

    def test_main_reports_another_job_in_the_same_store(self):
        """A stranger is named and disclaimed rather than silently excluded."""
        from baton_v12.job_manager import JobStore, submit
        from baton_v12.contracts import job_input_identity

        packet = self.main_packet()
        stranger = dict(self.submission, submission_id="sub-stranger",
                        jobs=[dict(fixtures.job(
                            "job-a-stranger",
                            input_digest=job_input_identity(self.manifest),
                            policy_digest=fixtures.POLICY_DIGEST,
                            stages=[fixtures.stage("implementation",
                                                   self.work)]))])
        with JobStore.open(packet["deployment"]["job_store"],
                           authority_uuid=packet["deployment"]["authority_uuid"],
                           incarnation="stranger-setup",
                           clock=lambda: fixtures.NOW) as job:
            submit(job, stranger)
        status, said, _driven = self.run_main(packet)
        self.assertEqual(status, 0, said)
        self.assertIn("job-a-stranger", said)
        outcome = json.loads(
            Path(packet["outcome_path"]).read_text(encoding="utf-8"))
        self.assertEqual(outcome["preexisting_jobs"], ["job-a-stranger"])
        self.assertIn("is NOT covered by this outcome",
                      outcome["accounting_scope"])
        self.assertEqual(len(outcome["admitted_attempts"]), 1)


def load_tests(loader, tests, pattern):
    """THIS FILE'S OWN CHECKS, and not the ones it inherits."""
    del tests, pattern, loader
    suite = unittest.TestSuite()
    for case in (TheDocumentedComposerRunsAsDocumented,
                 TheDocumentedSupervisorRunsThroughMain):
        for name in sorted(one for one in vars(case)
                           if one.startswith("test")):
            suite.addTest(case(name))
    return suite


del CHECKOUT
