"""The GENERATED packet, driven through the real entrypoint. W236087 R4.

Review 2026-09-22T11:53:11Z: "Drive the generated packet through its real
entrypoint using a fresh disposable Authority and deterministic engine/provider
fixtures... Exercise initial proposal, real changes-requested feedback delivery,
restoration, revised result/independent acceptance and failure/timeout cleanup
in one path." The earlier checks stopped short of that from both sides: the
supervisor cases composed their deployment from the accepted test fixture rather
than from `packet_bindings`, and the binding cases validated documents without
ever running one.

WHAT IS REAL HERE. `packet_bindings.compose` and `write` produce the deployment,
the sealed input manifest, the candidate context profile, the submission and
`PACKET.json`; `stage_execution.operations_from` composes THOSE bytes; and
`supervisor.supervise` drives them through `held_packet`, the owner acts, the
admission gate, the correction, the cancellation seam and the cleanup
accounting. The Authority is a fresh disposable one built through public APIs --
`create_work`, `add_route_handler`, `grant_capability` -- which is ordinary
deterministic fixture setup and touches no deployed instance.

WHAT IS NOT CLAIMED. The engine and the provider subprocess remain the two
accepted deterministic seams. No container, no image, no live provider, no
network, no credential, and no operator deployment is read or changed.
"""
import io
import json
import os
from pathlib import Path
import unittest
from unittest import mock

from baton_v12.contracts import digest
from tests.job_manager import fixtures
from tools import stage_execution

import packet_bindings
import supervisor
from test_supervisor import SupervisedCase

HERE = Path(__file__).resolve().parent
CHECKOUT = str(HERE.parents[4])
VECTORS = (Path(CHECKOUT) / "work/records/2026/08"
           / "finding-v12-isolated-agent-workers/findings"
           / "finding-v12-worker-contract/findings"
           / "finding-worker-control-api-manifests/evidence/vectors.json")
NETWORK = "baton-provider-egress"
# THE TREE THE SUPERVISOR'S OWN PROCESS REALLY IMPORTS. `baton_v12` resolves to
# `<PYTHON>/src/baton_v12` and `tools` to `<PYTHON>/tools`, so binding this root
# is binding the bytes this process is running -- which is what makes
# `verify_imported_sources` a proof here rather than a formality over a
# synthetic package.
PYTHON = Path(CHECKOUT) / "v12/python"


@unittest.skipUnless(VECTORS.exists(),
                     "the published worker-contract conformance vector is this "
                     "composition's real operand")
class TheGeneratedPacketDrivesTheRealEntrypoint(SupervisedCase):
    """One run, composed from the packet's own generated bytes.

    `generated` is a CLASS attribute so it exists before `setUp` runs: the
    inherited fixture asks for the composed document while building its own
    packet, which is the earliest this composition is reached.
    """

    generated = None

    def setUp(self):
        self.generated = None
        super().setUp()

    # -- the deployment under test IS the generated one ----------------------

    def selections(self):
        """Every operand, taken from THIS case's own disposable identities.

        The participants, principals, routes and grants are the ones
        `ServingCase` registered against its fresh Authority; the workspace,
        launch and credential roots are the ones this composition already
        configured. Nothing here points at an operator deployment.
        """
        return {
            "instance": {
                "authority_store": self.authority_path,
                "authority_uuid": self.config["authority_uuid"],
                "integration_store": self.integration_store,
                "job_store": os.path.join(self.root, "jobs.sqlite3"),
                "control_store": os.path.join(self.root, "control.sqlite3"),
                "integration_profile": {
                    "profile_kind": "git", "profile_version": 1,
                    "integrator_participant": "baton.integrator",
                    "instructions_digest": "sha256:" + "e" * 64},
                "retention_policy_digest":
                    self.config["retention_policy_digest"],
                "runtime_path": self.written_runtime_root(),
                "build_commit": "1e576ff2186db69e8b44da9d38874ff7e99ebbe3"},
            "source_root": self.source,
            "image_reference": "baton-v12-claude-worker:deterministic",
            "image_digest": self.config["image_digest"],
            "cli_build": "2.1.247",
            "manager_source": str(self.packet_root / "manager-source"),
            "supervisor_path": str(HERE / "supervisor.py"),
            "vectors": str(VECTORS),
            "credential_sources": None,
            "credential_profile": {"api": {"provider": "fixture",
                                           "reference": "fixture/one"}},
            "evidence_digest": digest({"deterministic": "composition proof"}),
            "provider_network": NETWORK,
            "run_id": self.RUN, "work": "W236087", "claim": 238462,
            "note": "the generated packet, driven deterministically",
            "places": {"workspaces": self.storage,
                       "private-contexts": str(self.context_root)},
            "participants": {
                "work_id": self.work,
                "implementation": self.config["participant"],
                "implementation_principal": self.config["principal"],
                "review": "baton.reviewer",
                "review_principal": self.principals["baton.reviewer"],
                "receipts": {"verification": "baton.verifier",
                             "review": "baton.approver-review",
                             "approval": "baton.approver"},
                "worker_files": {"opt/baton/claude_agent.py": "0" * 64},
                "fixture_files": {"harness.py": self.digest_of(
                    os.path.join(self.source, "harness.py"))}}}

    def written_runtime_root(self):
        place = self.packet_root / "runtime"
        place.mkdir(exist_ok=True)
        (place / "baton-v12-stack").write_bytes(b"#!/bin/sh\nexit 0\n")
        return str(place)

    def written_manager_source(self):
        place = self.packet_root / "manager-source" / "boundpkg"
        place.mkdir(parents=True, exist_ok=True)
        (place / "__init__.py").write_text("VERSION = 'bound'\n",
                                           encoding="utf-8")

    def imported_source(self):
        """The REAL `baton_v12` and `tools`, bound as the packet binds them.

        Review 2026-09-22T12:31:42Z: the composition cases bound a synthetic
        package, so `main` on that packet refused at the import check before it
        ever reached a store -- which proved nothing about `main`'s own
        lifecycle. This binds the tree this process actually imports from, so
        the check passes for the reason it exists.
        """
        files = {}
        for relative in ("src/baton_v12", "tools"):
            for base, dirs, names in os.walk(PYTHON / relative):
                dirs[:] = [one for one in sorted(dirs)
                           if one != "__pycache__"]
                for name in sorted(names):
                    if name.endswith(".pyc"):
                        continue
                    whole = os.path.join(base, name)
                    files[os.path.relpath(whole, PYTHON)] = \
                        self.digest_of(whole)
        return {"path": str(PYTHON), "packages": ["baton_v12", "tools"],
                "file_count": len(files), "files": files}

    def generate(self):
        """Compose and WRITE the packet, exactly as the operator command does."""
        if self.generated is None:
            self.run_root = os.path.join(self.root, "generated-run")
            self.written_manager_source()
            documents = packet_bindings.compose(
                base=self.base, run_root=self.run_root, **self.selections())
            places = packet_bindings.write(self.run_root, documents,
                                           checkout=self.checkout)
            # THE CERTIFIED PROFILE IS THE GENERATED ONE. The worker document
            # this composition will preflight names the composer's context
            # profile digest, so the profile the owner acts certify has to be
            # that same document -- otherwise the admission boundary refuses an
            # uncertified profile, which is the fixture disagreeing with itself
            # rather than anything about the packet.
            self.context_profile = documents["context-profile.json"]
            self.context_digest = digest(self.context_profile)
            # AND THE SUBMISSION IS THE GENERATED ONE TOO. Every stage is
            # compared against the Job's single input digest and against the
            # worker's configured policy and profile, so a submission composed
            # from the accepted fixture's manifest can be served by no worker
            # this deployment configures -- which is the assembly refusing to
            # reserve capacity for a stage nobody could serve, not a defect.
            self.submission = documents["submission.json"]
            self.generated = (documents, places)
        return self.generated

    def composed_document(self, **members):
        """THE GENERATED DEPLOYMENT, not the accepted test fixture's.

        This is the substitution the whole case exists to make: everything
        downstream -- the preflight, the five sessions, the pool, the launch
        documents, the mounts and the endings -- reads bytes `packet_bindings`
        produced.
        """
        del members
        documents, _places = self.generate()
        return documents["deployment.json"]

    def turn(self, control, role, attempt_id, roots, **operands):
        """One worker turn, adopted from the GENERATED launch home.

        The accepted harness adopts a delivery out of `self.config`'s single
        launch home; the generated deployment gives each role its own, which is
        what the composed workers actually write to. Pointing the helper at the
        role's real launch home is the whole of the difference -- everything it
        then drives is the ordinary worker entry over the ordinary exchange.
        """
        documents, _places = self.generate()
        workers = {one["role"]: one["deployment"]
                   for one in documents["deployment.json"]["workers"]}
        held = self.config["launch_home"]
        self.config["launch_home"] = workers[role]["launch_home"]
        try:
            return super().turn(control, role, attempt_id, roots, **operands)
        finally:
            self.config["launch_home"] = held

    def packet_for(self):
        """The generated `PACKET.json`, adapted to this case's own context.

        Two members are this fixture's rather than the composer's: the context
        profile the accepted `ManagedSessionResume` harness certifies, and the
        submission the supervised case submits. Everything else -- the bounds,
        the fixture binding, the manager source, the deployment path and
        digest -- is the generated packet's own.
        """
        _documents, places = self.generate()
        packet = json.loads(Path(places["PACKET.json"]).read_text(
            encoding="utf-8"))
        # The profile the composer emitted is the one this fixture certifies,
        # so only its PATH differs: the supervised case re-serializes it beside
        # its own packet and `held_packet` hashes what it is pointed at.
        packet["context"].update(
            profile_path=str(self.packet_root / "profile.json"),
            profile_sha256=self.digest_of(str(self.packet_root
                                              / "profile.json")),
            profile_digest=self.context_digest,
            storage_path=str(self.context_root))
        packet["submission"] = dict(
            packet["submission"],
            path=str(self.packet_root / "submission.json"),
            sha256=self.digest_of(str(self.packet_root / "submission.json")))
        packet["deployment"].update(
            job_store=str(Path(self.root) / "jobs.sqlite3"),
            control_store=str(Path(self.root) / "control.sqlite3"),
            authority_store=str(self.authority_path),
            authority_uuid=self.config["authority_uuid"],
            state_root=str(self.root))
        packet["supervisor"] = dict(self.packet["supervisor"])
        packet["outcome_path"] = str(self.packet_root / "generated-outcome.json")
        place = self.packet_root / "GENERATED-PACKET.json"
        place.write_text(json.dumps(packet, sort_keys=True, indent=2),
                         encoding="utf-8")
        self.generated_packet_path = str(place)
        return packet

    # -- the whole path, in one run -----------------------------------------

    def test_the_generated_deployment_completes_the_correction(self):
        """Initial proposal, real changes-requested feedback, restoration,
        revised result and independent acceptance -- over generated bytes."""
        packet = self.packet_for()
        _composed, outcome, _job, control = self.supervised(packet=packet)
        self.assertEqual(outcome["state"], "settled", outcome["held_because"])
        self.assertEqual(outcome["workload"]["modes"], ["open", "restore"])
        self.assertEqual(outcome["workload"]["dispositions"],
                         ["changes-requested", "accepted"])
        self.assertEqual(len(set(outcome["workload"]["proposal_heads"])), 2)
        self.assertEqual(outcome["outstanding_cleanup"], [])
        self.assertEqual(outcome["uncertainty"], [])
        self.assertIs(outcome["final_canonical_read"], True)
        # THE PROVIDER REALLY SAW A RESUME, and the feedback reached it.
        calls = [json.loads(line)
                 for line in self.calls.read_text().splitlines()]
        self.assertEqual([one["restored"] for one in calls], [False, True])
        self.assertIn("THE REVIEW'S FINDINGS:", calls[1]["argv"][-1])
        del control

    def test_the_generated_packet_is_the_one_held_packet_accepts(self):
        packet = self.packet_for()
        held = supervisor.held_packet(self.generated_packet_path)
        self.assertEqual(held["bounds"], packet["bounds"])
        self.assertEqual(held["deployment"]["config_sha256"],
                         self.digest_of(held["deployment"]["config_path"]))

    def test_the_generated_deployment_passes_the_managers_own_validator(self):
        documents, _places = self.generate()
        given = stage_execution.held_configuration(documents["deployment.json"],
                                                   checkout=self.checkout)
        self.assertEqual(sorted(one["role"] for one in given["workers"]),
                         ["implementation", "review"])
        for one in given["workers"]:
            with self.subTest(role=one["role"]):
                self.assertEqual(one["deployment"]["network"], NETWORK)

    def test_completed_attempts_are_not_ordered_stopped(self):
        """A historical generation is not cancelled for its stage's sake.

        The correction leaves two implementation attempts behind. Neither is
        executing when the run ends, and the per-attempt facts -- not the
        stage's -- are what says so.
        """
        packet = self.packet_for()
        _composed, outcome, _job, _control = self.supervised(packet=packet)
        self.assertEqual(len(outcome["admitted_attempts"]), 4)
        for attempt, held in sorted(outcome["cancellation"].items()):
            with self.subTest(attempt=attempt):
                self.assertTrue(held["requested"])
                self.assertNotIn("answer", held)
                self.assertIn("this manager observed the runtime", held["why"])
                self.assertEqual(held["execution_runtime"], "destroyed")

    def test_a_timeout_over_generated_bytes_stops_and_accounts(self):
        """The failure path of the same composition, in the same run shape."""
        packet = dict(self.packet_for(), bounds=dict(
            self.packet["bounds"], total_seconds=8, cleanup_seconds=3))
        job, control, composed = self.serving()
        ticks = iter(range(10000))
        outcome = supervisor.supervise(
            job, control, composed, packet, clock=lambda: fixtures.NOW,
            sleep=lambda seconds: None,
            monotonic=lambda: float(next(ticks)))
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        self.assertEqual(outcome["state"], "held")
        executing = [one for one, held in outcome["cancellation"].items()
                     if held.get("execution_runtime") == "running"]
        self.assertTrue(executing, outcome["cancellation"])
        for attempt in executing:
            self.assertTrue(outcome["cancellation"][attempt]["requested"])
        # THE ENGINE RECEIVED THE STOP for the exact runtime it started.
        stops = {argv[-1] for argv in self.engine.vectors if argv[1] == "stop"}
        self.assertTrue(stops)
        self.assertTrue({outcome["cancellation"][one]["runtime_id"]
                         for one in executing}.issubset(stops))
        # AND ORDERING IT IS STILL NOT PROOF OF ABSENCE.
        self.assertTrue(outcome["outstanding_cleanup"])


class TheGeneratedPacketRunsThroughMain(TheGeneratedPacketDrivesTheRealEntrypoint):
    """The OPERATOR ENTRYPOINT over generated bytes. W236087 R4.

    `main` is what step 6 runs, and until now nothing executed it end to end:
    the composition cases called `supervise` directly and checked `held_packet`
    beside it, so `main`'s own path -- the import binding, the engine question,
    opening both stores, the owner acts, composing the deployment and the exit
    status -- was never covered.

    THE TWO DETERMINISTIC SEAMS STAY WHERE THEY ARE. `main` already takes
    `compose` and `image_inspect` for a deployment to supply; the composition
    handed back here is the accepted simulated-engine one, and `time.sleep` is
    patched because the composed deployment has no daemon to run a container --
    the same boundary every other case in this dossier drives from the loop's
    injected wait. Everything between them is `main`'s own.
    """

    def main_packet(self, **bounds):
        """The generated packet, bound to the source this process imports."""
        packet = self.packet_for()
        packet["manager_source"] = self.imported_source()
        # THE CODE BOUNDARY IS `tools/`, the tree whose `__file__` the inferred
        # boundary was derived from and the one this correction exists about.
        # The fixture's disk-backed roots are siblings of `src/` and `tools/`,
        # not inside either, which is the same shape a relocated manager source
        # has beside its run root.
        packet["code_boundary"] = str(PYTHON / "tools")
        packet["deployment"] = dict(
            packet["deployment"],
            job_store=os.path.join(self.root, "main-jobs.sqlite3"),
            control_store=os.path.join(self.root, "main-control.sqlite3"))
        packet["outcome_path"] = str(self.packet_root / "main-outcome.json")
        if bounds:
            packet["bounds"] = dict(packet["bounds"], **bounds)
        place = self.packet_root / "MAIN-PACKET.json"
        place.write_text(json.dumps(packet, sort_keys=True, indent=2),
                         encoding="utf-8")
        self.main_packet_path = str(place)
        return packet

    def composing(self, driven):
        """`main`'s composition seam, answering the accepted simulated one."""
        def compose(packet, job, control, stream):
            del packet, stream
            composed = stage_execution.operations_from(
                self.composed_document(), job, control,
                engine_run=self.engine,
                credential_provider=lambda provider, reference: self.secret,
                clock=lambda: fixtures.NOW, checkout=self.checkout)
            # The accepted harness reaches this composition through
            # `_composed` when it drives a worker turn; `serving()` sets it and
            # `main` composes through this seam instead.
            self._composed = composed
            self.addCleanup(composed.close)
            driven.append((job, control, composed))
            return composed
        return compose

    def run_main(self, packet, *, drive):
        """`main`, with the container boundary driven from its own wait."""
        # NOTHING IS PREPARED HERE. Review 2026-09-22T12:55:41Z: this used to
        # configure the workspace store before `main`, an undocumented
        # deployment act the operator packet never named. `supervisor.prepare`
        # derives it from the validated deployment now, so the fixture supplies
        # only the two accepted seams.
        self.engine = self.quiescing()
        driven, stream = [], io.StringIO()
        inspect = mock.Mock(return_value={
            "Id": packet["worker_image"]["config_digest"]})

        def waiting(seconds):
            del seconds
            if drive and driven:
                job, control, composed = driven[-1]
                states = self.states(job, composed)
                if states.get("implementation") == "waiting":
                    return self.run_implementation(control, composed)
                if states.get("review") == "waiting":
                    return self.run_review(job, control, composed)
            return None

        with mock.patch.object(supervisor.time, "sleep", waiting):
            status = supervisor.main(
                ["--packet", self.main_packet_path,
                 "--incarnation", "generated-main"],
                stream=stream, compose=self.composing(driven),
                image_inspect=inspect)
        inspect.assert_called_once_with(packet["worker_image"]["reference"])
        return status, stream.getvalue(), driven

    # -- the two paths through the entrypoint --------------------------------

    def test_main_completes_the_correction_and_exits_zero(self):
        packet = self.main_packet()
        status, said, driven = self.run_main(packet, drive=True)
        self.assertEqual(status, 0, said)
        self.assertTrue(driven, "main never composed the deployment")
        outcome = json.loads(
            Path(packet["outcome_path"]).read_text(encoding="utf-8"))
        self.assertEqual(outcome["state"], "settled", outcome["held_because"])
        self.assertEqual(outcome["workload"]["modes"], ["open", "restore"])
        self.assertEqual(outcome["workload"]["dispositions"],
                         ["changes-requested", "accepted"])
        self.assertEqual(outcome["outstanding_cleanup"], [])
        # AND MAIN OPENED ITS OWN STORES, which is half of what it adds.
        self.assertTrue(os.path.exists(
            packet["deployment"]["job_store"]))
        self.assertTrue(os.path.exists(
            packet["deployment"]["control_store"]))

    def test_main_holds_and_exits_one_when_the_bound_elapses(self):
        packet = self.main_packet(total_seconds=3, cleanup_seconds=2)
        status, said, _driven = self.run_main(packet, drive=False)
        self.assertEqual(status, 1, said)
        outcome = json.loads(
            Path(packet["outcome_path"]).read_text(encoding="utf-8"))
        self.assertEqual(outcome["state"], "held")
        self.assertEqual(outcome["stopped"], "overall-bound-exceeded")
        # THE RUNTIME IT STARTED WAS ORDERED STOPPED, through the real seam.
        executing = [one for one, held in outcome["cancellation"].items()
                     if held.get("execution_runtime") == "running"]
        self.assertTrue(executing, outcome["cancellation"])
        stops = {argv[-1] for argv in self.engine.vectors if argv[1] == "stop"}
        self.assertTrue({outcome["cancellation"][one]["runtime_id"]
                         for one in executing}.issubset(stops))
        self.assertTrue(outcome["outstanding_cleanup"])

    def test_main_prepares_the_workspace_store_from_the_deployment(self):
        """R4: the prerequisite the fixture used to supply, supplied by main.

        `configure_context_storage` reads the configured workspace root
        immediately, and the ordinary composition records it later, so a fresh
        run had nothing to read. `prepare` now derives it from the deployment
        the packet is bound to -- not from a root of its own choosing.
        """
        from baton_v12.worker_manager import ControlStore

        packet = self.main_packet()
        status, said, _driven = self.run_main(packet, drive=True)
        self.assertEqual(status, 0, said)
        with ControlStore.open(packet["deployment"]["control_store"],
                               incarnation="reading-back",
                               clock=lambda: fixtures.NOW) as control:
            from baton_v12.worker_manager.workspaces import (
                configured_workspace_storage)

            self.assertEqual(configured_workspace_storage(control).place,
                             self.storage)
        # AND IT IS THE DEPLOYMENT'S OWN ROOT, read from the configuration.
        documents, _places = self.generate()
        for one in documents["deployment.json"]["workers"]:
            self.assertEqual(one["deployment"]["workspace_storage"],
                             self.storage)

    def test_workers_naming_two_workspace_stores_refuse(self):
        """Choosing between them is not this program's decision."""
        documents, places = self.generate()
        held = json.loads(
            Path(places["deployment.json"]).read_text(encoding="utf-8"))
        held["workers"][1]["deployment"]["workspace_storage"] = str(
            Path(self.root) / "another-store")
        Path(places["deployment.json"]).write_text(
            json.dumps(held, sort_keys=True, indent=2), encoding="utf-8")
        packet = dict(self.packet_for())
        packet["deployment"] = dict(
            packet["deployment"],
            config_path=places["deployment.json"],
            config_sha256=self.digest_of(places["deployment.json"]))
        with self.assertRaisesRegex(supervisor.SupervisorRefusal,
                                    "name 2 workspace stores"):
            supervisor._workspace_root(packet)
        del documents

    def test_main_refuses_a_packet_whose_imported_source_is_not_bound(self):
        """R3's check, proved at the entrypoint rather than described.

        The composition fixture's synthetic package is exactly the case: the
        packet binds a tree this process does not import from, and `main`
        refuses with exit 2 before a store is opened or the engine is asked.
        """
        self.packet_for()
        stream = io.StringIO()
        inspect = mock.Mock(side_effect=AssertionError("never reached"))
        status = supervisor.main(
            ["--packet", self.generated_packet_path,
             "--incarnation", "generated-main-refusal"],
            stream=stream, image_inspect=inspect,
            compose=lambda *a, **k: self.fail("main composed after refusing"))
        self.assertEqual(status, 2)
        inspect.assert_not_called()
        self.assertIn("refused before anything opened", stream.getvalue())
        self.assertIn("outside the bound manager source", stream.getvalue())


class TheLiveRunShapeIsReportedHonestly(TheGeneratedPacketDrivesTheRealEntrypoint):
    """The first live run's shape, over generated bytes. LIVE-RUN-239365.md.

    One implementation runtime starts and its turn fails; the review stage
    never leaves `blocked`, and it carries an episode identity the status
    projection reports but for which no runtime was ever allocated. The live
    run counted that identity as a started runtime and produced three
    held-reasons about it, which buried the one real failure.

    THE STOP REASON DIFFERS FROM THE LIVE RUN'S and that is not the subject
    here: a failed turn in this harness leaves the stage waiting rather than
    reaching an ending, so the run stops at its own bound instead of at
    `exceptional`. What is under test is the CLASSIFICATION, which is the same
    either way -- one runtime started, one identity never allocated.
    """

    def driver(self, job, control, composed, **operands):
        del operands

        def wait(seconds):
            del seconds
            if self.states(job, composed).get("implementation") == "waiting":
                attempt = self.pending(composed, "implementation")
                if attempt is None:
                    return None
                self.turned.add(attempt)
                # THE TURN FAILS. What the live provider did was answer with a
                # review verdict and publish no proposal; either way the
                # implementation contract is unsatisfied and the stage ends
                # exceptional, which is the shape under test here.
                return self.turn(
                    control, "implementation", attempt,
                    self.mounted(composed, "implementation", attempt),
                    status=1)
            return None
        return wait

    def bounded(self):
        packet = dict(self.packet_for(), bounds=dict(
            self.packet["bounds"], total_seconds=12, cleanup_seconds=3))
        return self.supervised(packet=packet)

    def test_a_never_allocated_episode_is_named_and_not_charged_cleanup(self):
        _composed, outcome, _job, _control = self.bounded()
        self.assertEqual(outcome["state"], "held")
        self.assertEqual(outcome["admissions"],
                         {"implementation": 1, "review": 0})
        self.assertEqual(outcome["stage_states"]["review"], "blocked")
        unallocated = outcome["unallocated_attempts"]
        self.assertTrue(unallocated, outcome["attempt_origins"])
        for attempt in unallocated:
            with self.subTest(attempt=attempt):
                self.assertEqual(outcome["attempt_origins"][attempt],
                                 supervisor.UNALLOCATED)
                # NOT CHARGED A DESTROY RECORD THAT COULD NOT EXIST.
                self.assertNotIn(attempt, outcome["cleanup"])
                self.assertNotIn(attempt, outcome["outstanding_cleanup"])
                # AND NO STOP WAS ORDERED FOR IT.
                self.assertTrue(outcome["cancellation"][attempt]["requested"])
                self.assertIn("holds no attempt row for this identity",
                              outcome["cancellation"][attempt]["why"])
                # AND IT IS NOT REPORTED AS A LEAK.
                self.assertNotIn(f"execution on {attempt} was not stopped",
                                 " ".join(outcome["held_because"]))

    def test_the_started_runtime_is_still_fully_accounted_for(self):
        _composed, outcome, _job, _control = self.bounded()
        started = [one for one, origin in outcome["attempt_origins"].items()
                   if origin == supervisor.STARTED]
        self.assertEqual(len(started), 1, outcome["attempt_origins"])
        # The runtime this run launched is accounted for exactly as before.
        self.assertIn(started[0], outcome["cleanup"])
        said = " ".join(outcome["held_because"])
        self.assertIn("the packet declares 2 implementer invocation(s) and "
                      "this run has 1", said)
        self.assertIn("the selected sequence is ['open', 'restore']", said)


def load_tests(loader, tests, pattern):
    """This file's own checks; the inherited supervisor cases stay put."""
    del tests, pattern
    suite = unittest.TestSuite()
    for case in (TheGeneratedPacketDrivesTheRealEntrypoint,
                 TheGeneratedPacketRunsThroughMain,
                 TheLiveRunShapeIsReportedHonestly):
        for name in sorted(one for one in vars(case)
                           if one.startswith("test")):
            suite.addTest(case(name))
    return suite
