#!/usr/bin/env python3
"""Deploy the v11 `baton-work` product into an EXPLICIT distribution root.

v11-ONLY, by the frozen-v10 ruling: this tool shares nothing with
`tools/deploy.py`, reads nothing from the v10 catalogs or release tree, and
never touches a v10 path. It exists so the Gate B handoff is a real install
command instead of hand-run zipapp steps.

The distribution model is WS-6's: an exact release directory is IMMUTABLE.
The target is an explicit path the operator names; it must not exist yet —
this tool never adopts, overwrites, or deletes. The layout is the ruled
release shape:

    <target>/bin/baton             executable zipapp (cli:entry)
    <target>/doc/BATON-WORK.md     the operator quickstart
    <target>/conf/baton.example.json  a complete valid config example
    <target>/tmpl/<pattern>.md     the numbered template ASSETS beside bin/
                                   (M6: never embedded in the zipapp)

The candidate is staged in a scratch directory beside the target and
published with one atomic rename: the visible state is the complete
distribution or nothing.

Usage:  python3 tools/deploy_work.py /explicit/target/dir
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import sys
import tempfile
import zipapp

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_PACKAGE = os.path.join(REPO, "src", "baton_work")
SOURCE_TEMPLATES = os.path.join(REPO, "tmpl")
# The complete distribution beyond the executable: documentation and a
# configuration example ride every release as immutable assets.
SOURCE_ASSETS = (
	("docs/BATON-WORK.md", "doc/BATON-WORK.md"),
	("docs/BATON-SETUP.md", "doc/BATON-SETUP.md"),
	("conf/baton.example.json", "conf/baton.example.json"),
)


def fail(message: str) -> "NoReturn":
	print(json.dumps({"error": message}), file=sys.stderr)
	raise SystemExit(1)


def main(argv=None) -> int:
	argv = sys.argv[1:] if argv is None else argv
	if len(argv) != 1 or argv[0].startswith("-"):
		fail("usage: deploy_work.py TARGET_DIR — the explicit v11 "
		     "distribution root to create; nothing is inferred and "
		     "nothing existing is touched")
	target = os.path.abspath(argv[0])
	if os.path.lexists(target):
		fail(f"{target} already exists; an exact release directory is "
		     f"immutable — deploy each release into a NEW explicit "
		     f"directory, never over an old one")
	parent = os.path.dirname(target)
	if not os.path.isdir(parent):
		fail(f"{parent} is not an existing directory; create the "
		     f"parent first — deploy writes only where you chose")
	if not os.path.isdir(SOURCE_PACKAGE) or \
			not os.path.isdir(SOURCE_TEMPLATES):
		fail(f"this checkout is incomplete: expected {SOURCE_PACKAGE} "
		     f"and {SOURCE_TEMPLATES}")

	scratch = tempfile.mkdtemp(prefix=".deploy-work-", dir=parent)
	try:
		staging = os.path.join(scratch, "app")
		# R111: candidate assembly carries INTENTIONAL sources only —
		# host-generated bytecode never becomes release content.
		shutil.copytree(SOURCE_PACKAGE,
		                os.path.join(staging, "baton_work"),
		                ignore=shutil.ignore_patterns(
		                    "__pycache__", "*.pyc", "*.pyo"))
		os.mkdir(os.path.join(scratch, "bin"))
		archive = os.path.join(scratch, "bin", "baton")
		# cli:entry, NOT cli:main — zipapp discards the target's return
		# value, which turned refusals into exit 0 (the WF-06 lesson).
		zipapp.create_archive(staging, archive,
		                      interpreter="/usr/bin/env python3",
		                      main="baton_work.cli:entry")
		os.chmod(archive, 0o755)
		shutil.rmtree(staging)
		templates = sorted(name for name in os.listdir(SOURCE_TEMPLATES)
		                   if name.endswith(".md"))
		if not templates:
			fail(f"{SOURCE_TEMPLATES} holds no numbered templates; "
			     f"refusing to publish an assetless distribution")
		os.mkdir(os.path.join(scratch, "tmpl"))
		for name in templates:
			shutil.copyfile(os.path.join(SOURCE_TEMPLATES, name),
			                os.path.join(scratch, "tmpl", name))
		for source_rel, target_rel in SOURCE_ASSETS:
			source = os.path.join(REPO, source_rel)
			if not os.path.isfile(source):
				fail(f"this checkout is incomplete: {source} is "
				     f"missing; refusing to publish a partial "
				     f"distribution")
			destination = os.path.join(scratch, target_rel)
			os.makedirs(os.path.dirname(destination), exist_ok=True)
			shutil.copyfile(source, destination)
		with open(archive, "rb") as handle:
			digest = hashlib.sha256(handle.read()).hexdigest()
		os.rename(scratch, target)
	except BaseException:
		shutil.rmtree(scratch, ignore_errors=True)
		raise
	print(json.dumps({
		"target": target,
		"executable": os.path.join(target, "bin", "baton"),
		"archive_sha256": digest,
		"templates": templates,
		"next": f"{os.path.join(target, 'bin', 'baton')} init "
		        f"YOUR_COORDINATION_HOME",
	}, indent=2, sort_keys=True))
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
